import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const headers={"access-control-allow-origin":"*","access-control-allow-headers":"authorization, content-type, x-maxim-session","access-control-allow-methods":"GET,POST,PATCH,OPTIONS","content-type":"application/json; charset=utf-8","cache-control":"no-store"};
const reply=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers});
const sha256=async(value:string)=>Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value)))).map(b=>b.toString(16).padStart(2,"0")).join("");
function config(){const url=Deno.env.get("SUPABASE_URL")!;const keys=Deno.env.get("SUPABASE_SECRET_KEYS");const key=keys?JSON.parse(keys).default:Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;return{url,key};}
async function rest(path:string,init:RequestInit={}){const {url,key}=config();const res=await fetch(`${url}/rest/v1/${path}`,{...init,headers:{apikey:key,authorization:`Bearer ${key}`,"content-type":"application/json",prefer:"return=representation",...(init.headers||{})}});const text=await res.text();const data=text?JSON.parse(text):null;if(!res.ok)throw new Error(data?.message||`Database request failed (${res.status})`);return data;}
async function authorized(req:Request){const token=req.headers.get("x-maxim-session")||req.headers.get("authorization")?.replace(/^Bearer\s+/i,"")||"";if(!token)return false;const rows=await rest(`maxim_portal_sessions?token_sha256=eq.${await sha256(token)}&revoked_at=is.null&expires_at=gt.${encodeURIComponent(new Date().toISOString())}&select=token_sha256`);return rows.length===1;}
const defaultContext=()=>({status:"pending",updated_at:new Date().toISOString(),related_threads:[],decisions:[],open_questions:[],related_cards:[],implementation:{repository:null,branch:null,commit:null,important_paths:[],status:"unverified"}});
const short=(value:any,max:number)=>String(value??"").slice(0,max);
const cleanThread=(value:any)=>({id:short(value?.id,100),source:["codex","chatgpt","other"].includes(value?.source)?value.source:"other",title:short(value?.title,180),relevance:short(value?.relevance,40),reason:short(value?.reason,500),confidence:Math.max(0,Math.min(1,Number(value?.confidence??0))),review_status:["confirmed","needs_review","rejected"].includes(value?.review_status)?value.review_status:"needs_review"});
const cleanRelatedCard=(value:any)=>({id:short(value?.id,100)||null,title:short(value?.title,180),relationship:short(value?.relationship,100),confidence:Math.max(0,Math.min(1,Number(value?.confidence??0))),review_status:["confirmed","needs_review","rejected"].includes(value?.review_status)?value.review_status:"needs_review"});
const cleanImplementation=(value:any)=>({repository:value?.repository?short(value.repository,500):null,branch:value?.branch?short(value.branch,180):null,commit:value?.commit?short(value.commit,80):null,important_paths:Array.isArray(value?.important_paths)?value.important_paths.map((x:any)=>short(x,500)).slice(0,50):[],status:short(value?.status||"unverified",500)});
const cleanContext=(value:any)=>{const c=value&&typeof value==="object"&&!Array.isArray(value)?value:{};return{status:["pending","enriched","needs_review"].includes(c.status)?c.status:"pending",updated_at:new Date().toISOString(),related_threads:Array.isArray(c.related_threads)?c.related_threads.slice(0,25).map(cleanThread):[],decisions:Array.isArray(c.decisions)?c.decisions.map((x:any)=>short(x,1000)).slice(0,50):[],open_questions:Array.isArray(c.open_questions)?c.open_questions.map((x:any)=>short(x,1000)).slice(0,50):[],related_cards:Array.isArray(c.related_cards)?c.related_cards.slice(0,25).map(cleanRelatedCard):[],implementation:cleanImplementation(c.implementation)};};
const clean=(body:any)=>({title:String(body.title||"").trim().slice(0,180),project:String(body.project||"LanderWare").trim().slice(0,100),owner:String(body.owner||"Brian").trim().slice(0,80),lane:["doing","next","decision","parked"].includes(body.lane)?body.lane:"parked",value_score:Math.max(0,Number(body.value_score??5)),work_score:Math.max(.25,Number(body.work_score??5)),summary:String(body.summary||"").slice(0,2000),details:String(body.details||"").slice(0,20000),flags:Array.isArray(body.flags)?body.flags.map(String).slice(0,10):[],brian_override:Boolean(body.brian_override),manual_rank:body.manual_rank==null?null:Number(body.manual_rank),context_manifest:cleanContext(body.context_manifest),updated_at:new Date().toISOString()});
async function list(){const cards=await rest("production_board_cards?select=*&order=updated_at.desc");const thoughts=await rest("production_board_thoughts?select=*&order=created_at.desc");const activity=await rest("production_board_activity?select=*&order=created_at.desc&limit=1000");return reply({cards:cards.map((c:any)=>({...c,run_score:Number(c.value_score)/Number(c.work_score),thoughts:thoughts.filter((n:any)=>n.card_id===c.id),activity:activity.filter((a:any)=>a.card_id===c.id)}))});}
async function addCard(req:Request){const body=clean(await req.json().catch(()=>({})));if(!body.title)return reply({error:"Title is required."},400);const [card]=await rest("production_board_cards",{method:"POST",body:JSON.stringify(body)});await rest("production_board_activity",{method:"POST",body:JSON.stringify({card_id:card.id,action:"created",detail:{lane:card.lane}})});return reply({card},201);}
async function updateCard(req:Request,id:string){const before=(await rest(`production_board_cards?id=eq.${id}&select=*`))[0];if(!before)return reply({error:"Card not found."},404);const body=clean({...before,...await req.json().catch(()=>({}))});const [card]=await rest(`production_board_cards?id=eq.${id}`,{method:"PATCH",body:JSON.stringify(body)});await rest("production_board_activity",{method:"POST",body:JSON.stringify({card_id:id,action:before.lane===card.lane?"updated":"moved",detail:{from:before.lane,to:card.lane,value:card.value_score,work:card.work_score,run_score:Number(card.value_score)/Number(card.work_score)}})});return reply({card});}
async function addThought(req:Request,id:string){const body=await req.json().catch(()=>({}));const text=String(body.body||"").trim().slice(0,10000);if(!text)return reply({error:"Thought is required."},400);const [thought]=await rest("production_board_thoughts",{method:"POST",body:JSON.stringify({card_id:id,body:text,author:String(body.author||"Brian").slice(0,80)})});await rest("production_board_activity",{method:"POST",body:JSON.stringify({card_id:id,action:"thought_added",detail:{thought_id:thought.id}})});await rest(`production_board_cards?id=eq.${id}`,{method:"PATCH",body:JSON.stringify({updated_at:new Date().toISOString()})});return reply({thought},201);}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers});try{if(!(await authorized(req)))return reply({error:"Unauthorized"},401);const parts=new URL(req.url).pathname.split("/").filter(Boolean);const route=parts.slice(parts.indexOf("production-board")+1);if(req.method==="GET"&&!route.length)return list();if(req.method==="POST"&&!route.length)return addCard(req);if(req.method==="PATCH"&&route[0])return updateCard(req,route[0]);if(req.method==="POST"&&route[0]&&route[1]==="thoughts")return addThought(req,route[0]);return reply({error:"Not found"},404);}catch(error){return reply({error:error instanceof Error?error.message:"Unexpected error"},500);}});
