import "jsr:@supabase/functions-js/edge-runtime.d.ts";

// Dockmaster: one watch floor should surface every operational exception before it drifts into another silo.

const headers={"access-control-allow-origin":"*","access-control-allow-headers":"authorization, content-type, x-maxim-session","access-control-allow-methods":"GET,POST,PATCH,OPTIONS","content-type":"application/json; charset=utf-8","cache-control":"no-store"};
const reply=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers});
const sha256=async(value:string)=>Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value)))).map(b=>b.toString(16).padStart(2,"0")).join("");
function config(){const url=Deno.env.get("SUPABASE_URL")!;const keys=Deno.env.get("SUPABASE_SECRET_KEYS");const key=keys?JSON.parse(keys).default:Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;return{url,key};}
async function rest(path:string,init:RequestInit={}){const {url,key}=config();const res=await fetch(`${url}/rest/v1/${path}`,{...init,headers:{apikey:key,authorization:`Bearer ${key}`,"content-type":"application/json",prefer:"return=representation",...(init.headers||{})}});const text=await res.text();const data=text?JSON.parse(text):null;if(!res.ok)throw new Error(data?.message||`Database request failed (${res.status})`);return data;}
async function authorized(req:Request){const token=req.headers.get("x-maxim-session")||req.headers.get("authorization")?.replace(/^Bearer\s+/i,"")||"";if(!token)return false;const rows=await rest(`maxim_portal_sessions?token_sha256=eq.${await sha256(token)}&revoked_at=is.null&expires_at=gt.${encodeURIComponent(new Date().toISOString())}&select=token_sha256`);return rows.length===1;}
const clean=(body:any)=>({title:String(body.title||"").trim().slice(0,180),project:String(body.project||"LanderWare").trim().slice(0,100),owner:String(body.owner||"Brian").trim().slice(0,80),lane:["doing","next","decision","parked"].includes(body.lane)?body.lane:"parked",value_score:Math.max(0,Number(body.value_score??5)),work_score:Math.max(.25,Number(body.work_score??5)),summary:String(body.summary||"").slice(0,2000),details:String(body.details||"").slice(0,20000),flags:Array.isArray(body.flags)?body.flags.map(String).slice(0,10):[],brian_override:Boolean(body.brian_override),manual_rank:body.manual_rank==null?null:Number(body.manual_rank),updated_at:new Date().toISOString()});
async function list(){const cards=await rest("production_board_cards?select=*&order=updated_at.desc");const thoughts=await rest("production_board_thoughts?select=*&order=created_at.desc");const activity=await rest("production_board_activity?select=*&order=created_at.desc&limit=1000");return reply({cards:cards.map((c:any)=>({...c,run_score:Number(c.value_score)/Number(c.work_score),thoughts:thoughts.filter((n:any)=>n.card_id===c.id),activity:activity.filter((a:any)=>a.card_id===c.id)}))});}

type AttentionItem={key:string;severity:"critical"|"due"|"watch";source:string;title:string;detail:string;count:number;occurred_at?:string|null;due_at?:string|null;action_url:string};
const item=(value:AttentionItem)=>value;
async function attention(){
  const now=new Date(),nowIso=now.toISOString(),ninety=new Date(now.getTime()+90*86400000).toISOString(),sevenAgo=new Date(now.getTime()-7*86400000).toISOString();
  const [cards,emails,qualifications,closeouts,materials,inquiries,maximRequests,imports]=await Promise.all([
    rest("session_card_processing?status=neq.complete&select=class_session_id,status,cards_required,cards_issued,missing_requirements,updated_at,class_sessions(external_class_id,start_at,status)&order=updated_at.asc"),
    rest("transactional_email_outbox?status=in.(pending,failed)&select=id,status,notification_type,recipient_email,attempt_count,last_error,class_session_id,created_at&order=created_at.asc"),
    rest(`instructor_qualifications?status=eq.active&or=(expires_at.is.null,expires_at.lte.${encodeURIComponent(ninety)})&select=id,qualification_key,expires_at,people(id,display_name,email,active),courses(name,course_key)&order=expires_at.asc.nullsfirst`),
    rest(`class_sessions?end_at=lt.${encodeURIComponent(nowIso)}&status=not.in.(completed,cancelled)&select=id,external_class_id,status,start_at,end_at&order=end_at.asc&limit=100`),
    rest("accessory_attention_queue?fulfillment_status=neq.fulfilled&select=order_item_id,first_name,last_name,product_name,quantity,payment_status,fulfillment_status,created_at,external_class_id&order=created_at.asc&limit=100"),
    rest("requirement_inquiries?or=(delivery_status.is.null,delivery_status.neq.delivered)&select=id,name,email,delivery_status,submitted_at&order=submitted_at.asc&limit=100"),
    rest(`maxim_registration_requests?status=eq.requested&created_at=lt.${encodeURIComponent(sevenAgo)}&select=id,starts_at,billing_account,created_at,maxim_employee_profiles(first_name,last_name,email)&order=created_at.asc&limit=100`),
    rest("certification_import_files?inspection_status=not.in.(inspected,ignored)&select=id,source_file_name,inspection_status,rows_invalid,error_summary,last_inspected_at,created_at&order=created_at.asc&limit=100")
  ]);
  const items:AttentionItem[]=[];
  for(const row of cards){const remaining=Math.max(0,Number(row.cards_required||0)-Number(row.cards_issued||0)),session=row.class_sessions||{};items.push(item({key:`cards:${row.class_session_id}`,severity:row.status==="ready_for_issue"?"critical":"due",source:"Cards",title:`Issue ${remaining} card${remaining===1?"":"s"}`,detail:`${session.external_class_id||row.class_session_id} · ${row.cards_issued||0}/${row.cards_required||0} issued · ${row.status}`,count:remaining,occurred_at:session.start_at,due_at:row.updated_at,action_url:session.external_class_id?.startsWith("NHSO-")?`/corp/nhcso/?class=${encodeURIComponent(session.external_class_id)}`:`/admin/dashboard.html?session=${row.class_session_id}`}));}
  for(const row of emails)items.push(item({key:`email:${row.id}`,severity:row.status==="failed"?"critical":"due",source:"Notifications",title:`${row.status==="failed"?"Failed":"Pending"} ${String(row.notification_type||"notification").replaceAll("_"," ")}`,detail:`${row.recipient_email} · ${row.attempt_count||0} attempt${row.attempt_count===1?"":"s"}${row.last_error?` · ${row.last_error}`:""}`,count:1,occurred_at:row.created_at,action_url:row.class_session_id?`/admin/dashboard.html?session=${row.class_session_id}`:"/admin/dashboard.html#where-needed"}));
  for(const row of qualifications){const person=row.people||{},course=row.courses||{},unknown=!row.expires_at,expired=!unknown&&new Date(row.expires_at)<now;items.push(item({key:`qualification:${row.id}`,severity:expired?"critical":unknown?"due":"watch",source:"Instructor credentials",title:unknown?`Record ${person.display_name}'s expiration`:expired?`${person.display_name}'s credential expired`:`${person.display_name}'s credential expires soon`,detail:`${row.qualification_key}${course.name?` · ${course.name}`:""}${row.expires_at?` · ${new Date(row.expires_at).toLocaleDateString("en-US")}`:" · expiration unknown"}`,count:1,due_at:row.expires_at,action_url:`/admin/people.html?person=${encodeURIComponent(person.id||"")}`}));}
  for(const row of closeouts)items.push(item({key:`closeout:${row.id}`,severity:"critical",source:"Class closeout",title:"Close out a past class",detail:`${row.external_class_id||row.id} · ended ${new Date(row.end_at).toLocaleDateString("en-US")} · still ${row.status}`,count:1,occurred_at:row.end_at,action_url:`/admin/dashboard.html?session=${row.id}`}));
  for(const row of materials)items.push(item({key:`material:${row.order_item_id}`,severity:row.payment_status==="paid"?"critical":"due",source:"Materials",title:`Fulfill ${row.quantity||1} × ${row.product_name}`,detail:`${row.first_name||""} ${row.last_name||""} · payment ${row.payment_status||"unknown"} · fulfillment ${row.fulfillment_status||"pending"}`,count:Number(row.quantity||1),occurred_at:row.created_at,action_url:"/admin/dashboard.html#inboxPanel"}));
  for(const row of inquiries)items.push(item({key:`inquiry:${row.id}`,severity:"due",source:"Inquiries",title:`Respond to ${row.name||row.email||"course inquiry"}`,detail:`Delivery ${row.delivery_status||"unconfirmed"} · submitted ${new Date(row.submitted_at).toLocaleDateString("en-US")}`,count:1,occurred_at:row.submitted_at,action_url:"/admin/dashboard.html#where-needed"}));
  for(const row of maximRequests){const person=row.maxim_employee_profiles||{};items.push(item({key:`maxim:${row.id}`,severity:"due",source:"Maxim",title:`Resolve pending registration for ${[person.first_name,person.last_name].filter(Boolean).join(" ")||person.email||"employee"}`,detail:`Requested ${new Date(row.created_at).toLocaleDateString("en-US")} · ${row.billing_account||"billing unknown"}`,count:1,occurred_at:row.created_at,action_url:"/corp/maxim.html"}));}
  for(const row of imports)items.push(item({key:`import:${row.id}`,severity:Number(row.rows_invalid)>0||row.inspection_status==="failed"?"critical":"due",source:"Data imports",title:`Review ${row.source_file_name||"certification import"}`,detail:`${row.inspection_status||"unknown"} · ${row.rows_invalid||0} invalid row${row.rows_invalid===1?"":"s"}`,count:Math.max(1,Number(row.rows_invalid||0)),occurred_at:row.created_at,action_url:"/admin/dashboard.html#hotSyncAdmin"}));
  const rank={critical:0,due:1,watch:2};items.sort((a,b)=>rank[a.severity]-rank[b.severity]||String(a.due_at||a.occurred_at||"").localeCompare(String(b.due_at||b.occurred_at||"")));
  return reply({generated_at:nowIso,summary:{total:items.length,critical:items.filter(x=>x.severity==="critical").length,due:items.filter(x=>x.severity==="due").length,watch:items.filter(x=>x.severity==="watch").length},items});
}

async function addCard(req:Request){const body=clean(await req.json().catch(()=>({})));if(!body.title)return reply({error:"Title is required."},400);const [card]=await rest("production_board_cards",{method:"POST",body:JSON.stringify(body)});await rest("production_board_activity",{method:"POST",body:JSON.stringify({card_id:card.id,action:"created",detail:{lane:card.lane}})});return reply({card},201);}
async function updateCard(req:Request,id:string){const before=(await rest(`production_board_cards?id=eq.${id}&select=*`))[0];if(!before)return reply({error:"Card not found."},404);const body=clean({...before,...await req.json().catch(()=>({}))});const [card]=await rest(`production_board_cards?id=eq.${id}`,{method:"PATCH",body:JSON.stringify(body)});await rest("production_board_activity",{method:"POST",body:JSON.stringify({card_id:id,action:before.lane===card.lane?"updated":"moved",detail:{from:before.lane,to:card.lane,value:card.value_score,work:card.work_score,run_score:Number(card.value_score)/Number(card.work_score)}})});return reply({card});}
async function addThought(req:Request,id:string){const body=await req.json().catch(()=>({}));const text=String(body.body||"").trim().slice(0,10000);if(!text)return reply({error:"Thought is required."},400);const [thought]=await rest("production_board_thoughts",{method:"POST",body:JSON.stringify({card_id:id,body:text,author:String(body.author||"Brian").slice(0,80)})});await rest("production_board_activity",{method:"POST",body:JSON.stringify({card_id:id,action:"thought_added",detail:{thought_id:thought.id}})});await rest(`production_board_cards?id=eq.${id}`,{method:"PATCH",body:JSON.stringify({updated_at:new Date().toISOString()})});return reply({thought},201);}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers});try{if(!(await authorized(req)))return reply({error:"Unauthorized"},401);const parts=new URL(req.url).pathname.split("/").filter(Boolean);const route=parts.slice(parts.indexOf("production-board")+1);if(req.method==="GET"&&route[0]==="attention")return attention();if(req.method==="GET"&&!route.length)return list();if(req.method==="POST"&&!route.length)return addCard(req);if(req.method==="PATCH"&&route[0])return updateCard(req,route[0]);if(req.method==="POST"&&route[0]&&route[1]==="thoughts")return addThought(req,route[0]);return reply({error:"Not found"},404);}catch(error){return reply({error:error instanceof Error?error.message:"Unexpected error"},500);}});
