import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const ORIGINS=new Set(["https://www.910cpr.com","https://910cpr.com","https://es.910cpr.com"]);
const env=(name:string)=>Deno.env.get(name)||"";
const clean=(value:unknown,max=500)=>String(value??"").trim().slice(0,max);
function cors(req:Request){const origin=req.headers.get("origin")||"";return{"Access-Control-Allow-Origin":ORIGINS.has(origin)?origin:"https://www.910cpr.com","Access-Control-Allow-Headers":"content-type,x-maxim-session","Access-Control-Allow-Methods":"GET,OPTIONS","Cache-Control":"no-store","Vary":"Origin"}}
function json(req:Request,body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...cors(req),"Content-Type":"application/json; charset=utf-8"}})}
async function sha256Text(value:string){const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return[...new Uint8Array(bytes)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function rest(path:string){const key=env("SUPABASE_SERVICE_ROLE_KEY"),url=env("SUPABASE_URL");if(!key||!url)throw Error("server_configuration");const r=await fetch(`${url}/rest/v1/${path}`,{headers:{apikey:key,Authorization:`Bearer ${key}`}});const body=await r.json().catch(()=>null);if(!r.ok)throw Error(`database_${r.status}`);return body}
async function authorized(req:Request){const token=clean(req.headers.get("x-maxim-session"));if(!token)return false;const hash=await sha256Text(token),now=encodeURIComponent(new Date().toISOString());const rows=await rest(`maxim_portal_sessions?token_sha256=eq.${hash}&revoked_at=is.null&expires_at=gt.${now}&select=token_sha256&limit=1`);return Array.isArray(rows)&&rows.length===1}
async function feedRows(){const r=await fetch("https://www.910cpr.com/data/schedule_future.json",{headers:{accept:"application/json"},cache:"no-store"});if(!r.ok)throw Error(`feed_${r.status}`);const body=await r.json();return(Array.isArray(body)?body:body.sessions||[]).filter((x:any)=>x&&x.start_at&&new Date(x.start_at).getTime()>Date.now()-86400000)}
async function databaseRows(){const select=["id","external_class_id","external_course_id","source","status","start_at","end_at","registration_status","registration_backend","visibility","price","max_students","registration_url","source_instructor_label","source_location_label","courses!class_sessions_course_id_fkey(name)","people!class_sessions_lead_instructor_id_fkey(display_name)","locations!class_sessions_location_id_fkey(name)"].join(",");return await rest(`class_sessions?record_scope=eq.operational&start_at=gte.${encodeURIComponent(new Date(Date.now()-86400000).toISOString())}&status=in.(scheduled,active,completed)&select=${select}&order=start_at.asc&limit=500`)}
function feedRecord(row:any){const price=row.price??row.mapped_price??null,publicClass=row.public_direct_booking===true;return{internal_id:null,external_class_id:clean(row.session_id)||null,external_course_id:clean(row.course_id)||null,course_name:clean(row.course_name||row.official_course_name),start_at:row.start_at,end_at:row.end_at||null,instructor_name:clean(row.lead_instructor_name),location_name:clean(row.location_display||row.location_name),source:"enrollware_public_feed",status:clean(row.session_status||"scheduled"),registration_status:clean(row.registration_status||"unknown"),visibility:publicClass?"public":"private",price,max_students:row.max_students??null,available_seats:row.available_seats??null,registration_url:row.registration_url||null,evidence:"feed_only",issues:[] as string[],registration_ready:false}}
function dbRecord(row:any){return{internal_id:row.id,external_class_id:clean(row.external_class_id)||null,external_course_id:clean(row.external_course_id)||null,course_name:clean(row.courses?.name),start_at:row.start_at,end_at:row.end_at||null,instructor_name:clean(row.people?.display_name||row.source_instructor_label),location_name:clean(row.locations?.name||row.source_location_label),source:clean(row.source),status:clean(row.status),registration_status:clean(row.registration_status),visibility:clean(row.visibility),price:row.price??null,max_students:row.max_students??null,available_seats:null,registration_url:row.registration_url||null,evidence:"database_only",issues:[] as string[],registration_ready:false}}
function health(row:any){const issues:string[]=[];if(!row.course_name)issues.push("Course missing");if(!row.start_at)issues.push("Date missing");if(!row.instructor_name)issues.push("Instructor missing");if(!row.location_name)issues.push("Location missing");if(row.visibility==="public"&&row.price==null)issues.push("Price missing");if(row.visibility==="public"&&!row.external_class_id)issues.push("Class ID missing");if(row.visibility==="public"&&row.registration_status==="open"&&row.evidence!=="both")issues.push("Not permanent");row.issues=issues;row.registration_ready=row.visibility==="public"&&row.registration_status==="open"&&row.evidence==="both"&&issues.length===0;return row}
function merge(feed:any[],database:any[]){const byExternal=new Map<string,any>(),unmatched:any[]=[];for(const raw of database){const row=dbRecord(raw);if(row.external_class_id)byExternal.set(row.external_class_id,row);else unmatched.push(row)}for(const raw of feed){const f=feedRecord(raw),d=f.external_class_id?byExternal.get(f.external_class_id):null;if(!d){unmatched.push(f);continue}byExternal.delete(f.external_class_id);unmatched.push({...f,...d,course_name:d.course_name||f.course_name,instructor_name:d.instructor_name||f.instructor_name,location_name:d.location_name||f.location_name,price:d.price??f.price,max_students:d.max_students??f.max_students,available_seats:f.available_seats,registration_url:d.registration_url||f.registration_url,evidence:"both"})}unmatched.push(...byExternal.values());return unmatched.map(health).sort((a,b)=>String(a.start_at).localeCompare(String(b.start_at)))}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(req)});if(req.method!=="GET")return json(req,{error:"method_not_allowed"},405);try{if(!await authorized(req))return json(req,{error:"unauthorized"},401);const[feed,database]=await Promise.all([feedRows(),databaseRows()]),sessions=merge(feed,database);return json(req,{ok:true,generated_at:new Date().toISOString(),summary:{total:sessions.length,feed_count:feed.length,database_count:database.length,both:sessions.filter(x=>x.evidence==="both").length,feed_only:sessions.filter(x=>x.evidence==="feed_only").length,database_only:sessions.filter(x=>x.evidence==="database_only").length,needs_attention:sessions.filter(x=>x.issues.length).length},sessions})}catch(error){console.error("class-registry",error);return json(req,{error:"registry_temporarily_unavailable"},500)}});
