import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import {PDFDocument,StandardFonts,rgb} from "npm:pdf-lib@1.17.1";
import {recipeFor} from "./manifest.ts";

const ORIGINS=new Set(["https://www.910cpr.com","https://910cpr.com"]), ACTIVE=new Set(["registered","confirmed","completed","active"]), FULFILLED=new Set(["shipped","delivered","fulfilled","complete","completed"]), BUCKET="preclass-packet-documents";
const clean=(v:unknown)=>String(v??"").trim();
function cors(origin:string){const h:Record<string,string>={"access-control-allow-headers":"content-type,x-hot-sync-admin-key","access-control-allow-methods":"POST,OPTIONS",vary:"Origin"};if(ORIGINS.has(origin))h["access-control-allow-origin"]=origin;return h}
function json(origin:string,body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...cors(origin),"content-type":"application/json; charset=utf-8","cache-control":"private, no-store"}})}
function config(){const url=Deno.env.get("SUPABASE_URL"),keys=Deno.env.get("SUPABASE_SECRET_KEYS"),key=keys?JSON.parse(keys).default:Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!key)throw Error("Supabase service configuration is unavailable");return{url,key}}
async function authorized(req:Request){const key=req.headers.get("x-hot-sync-admin-key")||"";return !!key&&(await fetch("https://schedule.910cpr.com/admin/hot-sync",{headers:{"x-hot-sync-admin-key":key}})).ok}
async function rest(path:string){const{url,key}=config(),r=await fetch(`${url}/rest/v1/${path}`,{headers:{apikey:key,authorization:`Bearer ${key}`}}),body=await r.json();if(!r.ok)throw Error(body?.message||`Database request failed (${r.status})`);return body}
async function source(path:string){const{url,key}=config(),r=await fetch(`${url}/storage/v1/object/authenticated/${BUCKET}/${path}`,{headers:{authorization:`Bearer ${key}`}});if(!r.ok)throw Error(`Required protected packet source is unavailable: ${path}`);return new Uint8Array(await r.arrayBuffer())}
export function outstanding(addons:any[]){return(addons||[]).filter(item=>!FULFILLED.has(clean(item.fulfillment_status||item.status).toLowerCase())&&!new Set(["manual_other_source","other_source","bring_own_manual"]).has(clean(item.key).toLowerCase()))}
function drawRoster(pdf:any,session:any,participants:any[],regular:any,bold:any){for(let offset=0;offset<Math.max(participants.length,1);offset+=10){const page=pdf.addPage([792,612]),rows=participants.slice(offset,offset+10),start=new Date(session.start_at);page.drawText("910CPR  |  AHA",{x:30,y:580,size:14,font:bold,color:rgb(.05,.23,.38)});page.drawText("PRECLASS IDENTITY VERIFICATION",{x:560,y:580,size:11,font:bold});page.drawText(clean(session.courses?.name||"Course"),{x:30,y:554,size:16,font:bold});page.drawText(`${start.toLocaleDateString("en-US",{timeZone:"America/New_York",dateStyle:"full"})} · ${start.toLocaleTimeString("en-US",{timeZone:"America/New_York",hour:"numeric",minute:"2-digit"})} · ${clean(session.locations?.name||session.source_location_label)}`,{x:30,y:534,size:10,font:regular});page.drawText(`Instructor: ${clean(session.people?.display_name||session.source_instructor_label||"Not assigned")}`,{x:30,y:518,size:10,font:regular});page.drawText("Verify your NAME and EMAIL. Clearly write any correction below.",{x:30,y:494,size:11,font:bold});let y=470;for(let i=0;i<10;i++,y-=42){const p=rows[i];page.drawRectangle({x:30,y:y-28,width:732,height:38,borderWidth:.6,borderColor:rgb(.45,.5,.55)});page.drawText(String(offset+i+1),{x:36,y:y-8,size:9,font:regular});if(p){page.drawText(clean(p.display_name),{x:58,y,size:12,font:bold});page.drawText(clean(p.email),{x:290,y,size:12,font:bold});page.drawText(clean(p.phone),{x:590,y,size:8,font:regular})}page.drawText("Correction:",{x:58,y:y-17,size:8,font:regular,color:rgb(.3,.35,.4)})}}}
function drawMaterials(pdf:any,materials:any[],regular:any,bold:any){const page=pdf.addPage([792,612]);page.drawText("Instructor Materials to Distribute",{x:30,y:575,size:16,font:bold});page.drawText("Only paid items that 910CPR still owes are shown.",{x:30,y:553,size:10,font:regular});["Student","Item","Qty","Fulfillment / status"].forEach((v,i)=>page.drawText(v,{x:[30,250,570,620][i],y:525,size:10,font:bold}));let y=503;for(const item of materials.slice(0,22)){page.drawText(clean(item.student),{x:30,y,size:9,font:regular});page.drawText(clean(item.name).slice(0,48),{x:250,y,size:9,font:regular});page.drawText(String(item.quantity||1),{x:575,y,size:9,font:regular});page.drawText(clean(item.status||"outstanding"),{x:620,y,size:9,font:regular});y-=21}if(!materials.length)page.drawText("No outstanding participant fulfillment obligations were found.",{x:30,y:500,size:10,font:regular})}
async function build(session:any,participants:any[],materials:any[],descriptors:boolean){const recipe=recipeFor(session.courses?.course_key||"");if(!recipe)throw Error(`No preclass packet recipe is configured for course ${session.courses?.course_key||"unknown"}`);const pdf=await PDFDocument.create(),regular=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold);drawRoster(pdf,session,participants,regular,bold);drawMaterials(pdf,materials,regular,bold);for(const document of [...recipe.documents].sort((a,b)=>a.order-b.order)){const input=await PDFDocument.load(await source(document.source));for(let person=0;person<participants.length;person++)for(const number of document.student_pages){const[copied]=await pdf.copyPages(input,[number-1]);pdf.addPage(copied)}if(descriptors)for(const number of document.descriptor_pages){const[copied]=await pdf.copyPages(input,[number-1]);pdf.addPage(copied)}}return pdf.save()}

Deno.serve(async req=>{const origin=req.headers.get("origin")||"";if(origin&&!ORIGINS.has(origin))return json(origin,{error:"Origin is not allowed"},403);if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(origin)});if(req.method!=="POST")return json(origin,{error:"Method not allowed"},405);try{if(!(await authorized(req)))return json(origin,{error:"Unauthorized"},401);const body=await req.json(),id=clean(body.sessionId);if(!/^[0-9a-f-]{36}$/i.test(id))return json(origin,{error:"A canonical session UUID is required"},400);const rows=await rest(`class_sessions?id=eq.${encodeURIComponent(id)}&record_scope=eq.operational&select=id,start_at,source_instructor_label,source_location_label,courses!class_sessions_course_id_fkey(name,course_key),people!class_sessions_lead_instructor_id_fkey(display_name),locations!class_sessions_location_id_fkey(name),registrations!registrations_class_session_id_fkey(id,status,customers!registrations_customer_id_fkey(first_name,last_name,email,phone))&limit=1`);if(!rows[0])return json(origin,{error:"Session not found"},404);const session=rows[0],participants=(session.registrations||[]).filter((r:any)=>ACTIVE.has(clean(r.status).toLowerCase())).map((r:any)=>({display_name:`${clean(r.customers?.first_name)} ${clean(r.customers?.last_name)}`.trim(),email:r.customers?.email,phone:r.customers?.phone}));const orders=await rest(`landerware_public_orders?class_session_id=eq.${encodeURIComponent(id)}&status=eq.paid&select=landerware_public_order_students(first_name,last_name,selected_addons)`),materials=orders.flatMap((o:any)=>(o.landerware_public_order_students||[]).flatMap((s:any)=>outstanding(s.selected_addons).map((item:any)=>({student:`${clean(s.first_name)} ${clean(s.last_name)}`.trim(),name:item.name||item.label||item.key,quantity:Number(item.quantity)||1,status:item.fulfillment_status||item.status||"outstanding"}))));const bytes=await build(session,participants,materials,body.printSkillsDescriptors===true);return new Response(bytes,{headers:{...cors(origin),"content-type":"application/pdf","content-disposition":`attachment; filename="preclass-packet-${id}.pdf"`,"cache-control":"private, no-store"}})}catch(error){console.error(JSON.stringify({event:"preclass_packet_error",message:String(error)}));return json(origin,{error:error instanceof Error?error.message:"Packet generation failed"},422)}});
