const test=require('node:test'),assert=require('node:assert/strict'),Filter=require('../docs/assets/class-finder-filter.js');
const fs=require('node:fs'),path=require('node:path');
function select(values){const listeners={};return{value:'',options:values.map(value=>({value,disabled:false,hidden:false})),get selectedOptions(){return this.options.filter(o=>o.value===this.value)},addEventListener(type,fn){listeners[type]=fn},change(value){this.value=value;listeners.change()}}}
function fixture(href='https://910cpr.com/classes/?date=2026-08-29'){
  const controls={course:select(['','BLS','ACLS']),date:select(['','2026-08-29','2026-08-30']),location:select(['','Shipyard','Offsite'])},cards=[{dataset:{course:'BLS',date:'2026-08-29',location:'Shipyard'},style:{}},{dataset:{course:'ACLS',date:'2026-08-29',location:'Offsite'},style:{}},{dataset:{course:'BLS',date:'2026-08-30',location:'Offsite'},style:{}}],count={textContent:''},empty={hidden:true},resetListeners={},reset={addEventListener(type,fn){resetListeners[type]=fn},click(){resetListeners.click()}},win={location:{href},history:{replaceState(_a,_b,next){win.location.href=new URL(next,'https://910cpr.com').href}}},controller=Filter.create({window:win,controls,cards,count,empty,reset});return{controls,cards,count,empty,reset,win,controller}}
test('date deep link initializes dropdown, filters Aug 29, and updates count',()=>{const x=fixture();assert.equal(x.controller.initializeFromUrl(),2);assert.equal(x.controls.date.value,'2026-08-29');assert.equal(x.count.textContent,'2 classes found');assert.deepEqual(x.cards.map(c=>c.hidden),[false,false,true])});
test('manual date selection updates the URL without reload',()=>{const x=fixture('https://910cpr.com/classes/');x.controller.initializeFromUrl();x.controls.date.change('2026-08-30');assert.equal(new URL(x.win.location.href).searchParams.get('date'),'2026-08-30');assert.equal(x.count.textContent,'1 class found')});
test('reset clears date parameter and all canonical filter state',()=>{const x=fixture();x.controller.initializeFromUrl();x.controls.course.value='BLS';x.reset.click();assert.equal(new URL(x.win.location.href).searchParams.has('date'),false);assert.deepEqual(x.controller.currentState(),{course:'',date:'',location:''});assert.equal(x.count.textContent,'3 classes found')});
test('course and date combine through the single controller path',()=>{const x=fixture();x.controller.initializeFromUrl();x.controls.course.change('BLS');assert.equal(x.count.textContent,'1 class found');assert.deepEqual(x.cards.map(c=>c.hidden),[false,true,true])});
test('location and date combine through the single controller path',()=>{const x=fixture();x.controller.initializeFromUrl();x.controls.location.change('Offsite');assert.equal(x.count.textContent,'1 class found');assert.deepEqual(x.cards.map(c=>c.hidden),[true,false,true])});
test('invalid and unsupported date parameters fall back safely and are removed',()=>{for(const href of ['https://910cpr.com/classes/?date=2026-02-30','https://910cpr.com/classes/?date=2027-01-01']){const x=fixture(href);x.controller.initializeFromUrl();assert.equal(x.controls.date.value,'');assert.equal(new URL(x.win.location.href).searchParams.has('date'),false)}});
test('Eastern boundary is compared as the rendered local calendar date, never reparsed as UTC',()=>{const card={course:'BLS',date:'2026-08-29',location:'Shipyard',start:'2026-08-30T00:30:00Z'};assert.equal(Filter.matches(card,{course:'',date:'2026-08-29',location:''}),true);assert.equal(Filter.matches(card,{course:'',date:'2026-08-30',location:''}),false)});
test('authoritative generator and rendered classes page load the same versioned controller',()=>{for(const file of ['../scripts/build_index_and_sitemap.py','../docs/classes/index.html'])assert.match(fs.readFileSync(path.join(__dirname,file),'utf8'),/\/assets\/class-finder-filter\.js\?v=20260829-1/)});
