const test=require('node:test'), assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {stripTypeScriptTypes}=require('node:module');
const root=require('node:path').resolve(__dirname,'..');
const shared=fs.readFileSync(root+'/supabase/functions/_shared/external-roster-proof.ts','utf8').replace(/export /g,'');
const owner=fs.readFileSync(root+'/supabase/functions/canonical-session-workspace/index.ts','utf8').replace(/^import .*;\r?\n/gm,'').replace(/export /g,'');
const context=vm.createContext({Date,Set,JSON,Deno:{serve(){},env:{get(){}}}});
vm.runInContext(stripTypeScriptTypes(shared+'\n'+owner)+'\nthis.api={registrationProof,summarizeSession};',context);
const api=context.api;
function row(){return {registration_backend:'enrollware',external_reconciliation:{complete:true,source_observed_at:new Date().toISOString(),active_external_registration_ids:['123'],active_registration_count:1},registrations:[{status:'registered',external_registration_id:'123',customers:{first_name:'Private',email:'private@example.test'}}]};}
test('complete source roster supplies a known canonical count and owner roster',()=>{const r=row();assert.equal(api.registrationProof(r).active_registration_count,1);assert.equal(api.summarizeSession(r).participants.length,1);});
test('stale source never becomes current because the endpoint was refreshed',()=>{const r=row();r.external_reconciliation.source_observed_at='2020-01-01T00:00:00Z';for(let i=0;i<2;i++){const p=api.summarizeSession(r);assert.equal(p.participant_count,null);assert.equal(p.participants.length,0);assert.equal(p.demand_status,'stale_reconciliation');}});
test('unknown, incomplete, mismatched and duplicate identities fail closed',()=>{for(const change of [r=>delete r.external_reconciliation,r=>r.external_reconciliation.complete=false,r=>r.registrations[0].external_registration_id='456',r=>r.external_reconciliation.active_external_registration_ids=['123','123'],r=>delete r.registrations]){const r=row();change(r);assert.equal(api.registrationProof(r).count_available,false);}});
test('last active registration removal requires a matching empty source roster',()=>{const r=row();r.registrations[0].status='canceled';assert.equal(api.registrationProof(r).active_registration_count,null);r.external_reconciliation.active_external_registration_ids=[];r.external_reconciliation.active_registration_count=0;assert.equal(api.registrationProof(r).active_registration_count,0);});
test('source timestamps in the future are not accepted',()=>{const r=row();r.external_reconciliation.source_observed_at=new Date(Date.now()+3600000).toISOString();assert.equal(api.registrationProof(r).count_available,false);});
test('native checkout with an external class still requires complete external roster evidence',()=>{const r={registration_backend:'landerware',external_class_id:'80001',registrations:[]};assert.equal(api.registrationProof(r).active_registration_count,null);assert.equal(api.registrationProof(r).demand_status,'external_reconciliation_required');});
test('native event slug is a local identity, not an Enrollware class',()=>{const r={registration_backend:'landerware',source:'landerware_event',external_class_id:'native-event-2030',registrations:[{status:'registered'}]};assert.equal(api.registrationProof(r).active_registration_count,1);assert.equal(api.registrationProof({...r,external_class_id:'80001'}).count_available,false);});
test('mixed native and reconciled seats count together without demanding native IDs in Enrollware',()=>{const r={...row(),registration_backend:'landerware',external_class_id:'80001'};r.registrations.push({status:'registered',registration_source:'landerware'});assert.equal(api.registrationProof(r).active_registration_count,2);r.external_reconciliation.source_observed_at='2020-01-01T00:00:00Z';assert.equal(api.registrationProof(r).active_registration_count,null);});
test('source-owned seat without an external ID is never silently ignored',()=>{const r={...row(),registration_backend:'landerware',external_class_id:'80001'};r.registrations.push({status:'registered',registration_source:'gmail_enrollware'});assert.equal(api.registrationProof(r).count_available,false);});
