import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const ORIGIN="https://www.910cpr.com",ALLOWED=new Set([ORIGIN,"https://910cpr.com"]),STRIPE_API="https://api.stripe.com/v1";
const cors=(origin:string)=>({"access-control-allow-origin":ALLOWED.has(origin)?origin:ORIGIN,"access-control-allow-headers":"content-type,idempotency-key","access-control-allow-methods":"GET,POST,OPTIONS","cache-control":"no-store",vary:"Origin"});
const json=(origin:string,data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{...cors(origin),"content-type":"application/json; charset=utf-8"}});
function cfg(){const url=Deno.env.get("SUPABASE_URL"),raw=Deno.env.get("SUPABASE_SECRET_KEYS"),key=raw?JSON.parse(raw).default:Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!key)throw Error("server_configuration");return{url,key}}
async function db(path:string,init:RequestInit={}){const{url,key}=cfg(),r=await fetch(`${url}/rest/v1/${path}`,{...init,headers:{apikey:key,authorization:`Bearer ${key}`,"content-type":"application/json",prefer:"return=representation",...(init.headers||{})}}),p=await r.json().catch(()=>({}));if(!r.ok)throw Error(p?.message||`database_${r.status}`);return p}
async function rpc(name:string,body:unknown){const p=await db(`rpc/${name}`,{method:"POST",body:JSON.stringify(body)});return Array.isArray(p)?p[0]:p}
async function scheduleSession(id:string){if(!/^\d+$/.test(id))throw Error("invalid_session");const r=await fetch(`${ORIGIN}/data/schedule_future.json`,{headers:{accept:"application/json"}});if(!r.ok)throw Error("public_schedule_unavailable");const p=await r.json(),rows=Array.isArray(p)?p:p.sessions||[],s=rows.find((x:any)=>String(x.session_id)===id&&x.public_direct_booking===true&&x.registration_status==="open");if(!s)throw Error("session_not_open");return s}
async function catalog(courseId:string){const rows=await db(`landerware_registration_catalog?course_id=eq.${encodeURIComponent(courseId)}&active=eq.true&select=course_id,course_name,unit_amount,currency,addons,billing_codes&limit=1`);if(!rows[0])throw Error("price_catalog_missing");return rows[0]}
function stripeKey(){const k=Deno.env.get("STRIPE_SECRET_KEY");if(!k)throw Error("stripe_unavailable");return k}
async function stripe(path:string,params:URLSearchParams,idempotencyKey:string){const r=await fetch(`${STRIPE_API}/${path}`,{method:"POST",headers:{authorization:`Bearer ${stripeKey()}`,"content-type":"application/x-www-form-urlencoded","Stripe-Version":Deno.env.get("STRIPE_API_VERSION")||"2026-07-29.dahlia","idempotency-key":idempotencyKey},body:params}),p=await r.json().catch(()=>({}));if(!r.ok)throw Error(p?.error?.message||`stripe_${r.status}`);return p}
async function stripeGet(path:string){const r=await fetch(`${STRIPE_API}/${path}`,{headers:{authorization:`Bearer ${stripeKey()}`,"Stripe-Version":Deno.env.get("STRIPE_API_VERSION")||"2026-07-29.dahlia"}),p=await r.json().catch(()=>({}));if(!r.ok)throw Error(p?.error?.message||`stripe_${r.status}`);return p}
async function order(id:string){const rows=await db(`landerware_public_orders?id=eq.${encodeURIComponent(id)}&select=*,landerware_public_order_students(*)&limit=1`);if(!rows[0])throw Error("order_not_found");return rows[0]}
function checkoutParams(o:any,c:any){const p=new URLSearchParams();p.set("line_items[0][price_data][currency]",o.currency);p.set("line_items[0][price_data][product_data][name]",`${c.course_name} registration (${o.landerware_public_order_students.length} student${o.landerware_public_order_students.length===1?"":"s"})`);p.set("line_items[0][price_data][unit_amount]",String(o.total));p.set("line_items[0][quantity]","1");p.set("mode","payment");p.set("customer_email",o.payer_email);p.set("success_url",`${ORIGIN}/register/?order=${o.id}&paid=1`);p.set("cancel_url",`${ORIGIN}/register/?recover=${o.recovery_token}`);p.set("expires_at",String(Math.floor(Date.now()/1000)+1800));p.set("metadata[landerware_order_id]",o.id);p.set("integration_identifier",`910cpr_retail_${crypto.randomUUID().replace(/[^a-z]/g,"").slice(0,8).padEnd(8,"x")}`);if(o.billing_code)p.set("metadata[billing_code]",o.billing_code);return p}
async function createCheckout(o:any,c:any){const checkout=await stripe("checkout/sessions",checkoutParams(o,c),`landerware-public-${o.id}`);await db(`landerware_public_orders?id=eq.${o.id}`,{method:"PATCH",body:JSON.stringify({status:"checkout_open",stripe_checkout_session_id:checkout.id,checkout_url:checkout.url,updated_at:new Date().toISOString()})});return checkout}
async function queueEmail(recipient:string,subject:string,body:string,template:string,idempotencyKey:string){await db("landerware_messages",{method:"POST",headers:{prefer:"resolution=ignore-duplicates,return=minimal"},body:JSON.stringify({template_key:template,channel:"email",recipient,subject,body_text:body,delivery_provider:"gmail",delivery_status:"pending",idempotency_key:idempotencyKey})})}
async function sendRecovery(o:any,s:any){const link=`${ORIGIN}/register/?recover=${o.recovery_token}`;await queueEmail(o.payer_email,`Complete your ${s.course_name||"910CPR"} registration`,`We saved your class selection for 30 minutes. Complete payment here:\n${link}\n\nIf the hold expires, the same link will recheck availability before payment.`,`retail-checkout-recovery-v2`,`public-order-recovery:${o.id}`)}
async function paidEmails(o:any,s:any){const students=o.landerware_public_order_students||[],names=students.map((x:any)=>`${x.first_name} ${x.last_name}`).join(", "),selected=students.flatMap((x:any)=>(x.selected_addons||[]).map((a:any)=>`${x.first_name} ${x.last_name}: ${a.key} x${a.quantity||1}`));await Promise.all([...new Set(students.map((x:any)=>String(x.email)))].map(to=>queueEmail(to,`Registration confirmed — ${s.course_name}`,`Your registration is confirmed for ${s.course_name}.\n\n${new Date(s.start_at).toLocaleString("en-US",{timeZone:"America/New_York"})}\n${s.location_display||s.location_name||""}\n\nStudents: ${names}`,`retail-paid-confirmation-v2`,`public-order-paid:${o.id}:${to.toLowerCase()}`)));if(selected.length)await queueEmail(Deno.env.get("FULFILLMENT_EMAIL")||"brian@910cpr.com",`Paid add-ons require fulfillment — ${s.course_name}`,`Order ${o.id} is paid. Do not auto-release codes or materials.\n\n${selected.join("\n")}`,`retail-addon-fulfillment-v2`,`public-order-fulfillment:${o.id}`)}
async function start(req:Request,origin:string){const b=await req.json(),id=String(b.sessionId||"").trim(),s=await scheduleSession(id),c=await catalog(String(s.course_id||s.course_number||"")),students=Array.isArray(b.students)?b.students:[],key=(req.headers.get("idempotency-key")||"").trim();if(!key)throw Error("invalid_order");const result=await rpc("landerware_create_public_order",{p_idempotency_key:`public-order:${key}`,p_external_class_id:id,p_course_id:c.course_id,p_payer_email:String(b.payerEmail||students[0]?.email||""),p_payer_phone:String(b.payerPhone||students[0]?.phone||""),p_students:students,p_billing_code:String(b.billingCode||"")||null}),o=await order(result.orderId);if(o.total===0){await rpc("landerware_finalize_public_order",{p_order_id:o.id,p_stripe_payment_intent_id:"no_payment_required"});await paidEmails(o,s);return json(origin,{ok:true,orderId:o.id,holdExpiresAt:o.hold_expires_at,checkoutUrl:`${ORIGIN}/register/?order=${o.id}&paid=1`,recoveryUrl:`${ORIGIN}/register/?recover=${o.recovery_token}`})}const checkout=o.checkout_url?{url:o.checkout_url}:await createCheckout(o,c);if(!result.idempotentReplay)await sendRecovery(o,s);return json(origin,{ok:true,orderId:o.id,holdExpiresAt:o.hold_expires_at,checkoutUrl:checkout.url,recoveryUrl:`${ORIGIN}/register/?recover=${o.recovery_token}`})}
async function recover(token:string,origin:string){if(!/^[0-9a-f-]{36}$/i.test(token))throw Error("invalid_recovery_token");const rows=await db(`landerware_public_orders?recovery_token=eq.${encodeURIComponent(token)}&select=*&limit=1`),o=rows[0];if(!o)throw Error("order_not_found");if(o.status==="paid")return json(origin,{ok:true,status:"paid",orderId:o.id});if(new Date(o.hold_expires_at)<=new Date()){await db(`landerware_public_orders?id=eq.${o.id}`,{method:"PATCH",body:JSON.stringify({status:"expired",updated_at:new Date().toISOString()})});return json(origin,{ok:false,status:"expired",sessionId:o.external_class_id},409)}return json(origin,{ok:true,status:o.status,checkoutUrl:o.checkout_url,holdExpiresAt:o.hold_expires_at})}
async function verifyPaid(id:string,origin:string){if(!/^[0-9a-f-]{36}$/i.test(id))throw Error("order_not_found");const o=await order(id);if(o.status==="paid")return json(origin,{ok:true,status:"paid"});const checkout=await stripeGet(`checkout/sessions/${encodeURIComponent(o.stripe_checkout_session_id||"")}`);if(checkout.payment_status!=="paid")return json(origin,{ok:false,status:"payment_pending"},409);await rpc("landerware_finalize_public_order",{p_order_id:o.id,p_stripe_payment_intent_id:String(checkout.payment_intent||"")});const s=await scheduleSession(o.external_class_id);await paidEmails(o,s);return json(origin,{ok:true,status:"paid"})}

function fallbackUrl(s:any,id:string){try{const u=new URL(String(s.registration_url||""));return u.origin==="https://coastalcprtraining.enrollware.com"&&u.pathname==="/enroll"&&u.searchParams.get("id")===id?u.toString():null}catch{return null}}
Deno.serve(async req=>{const origin=req.headers.get("origin")||"",parts=new URL(req.url).pathname.split("/").filter(Boolean),route=parts.slice(parts.indexOf("public-registration")+1);if(origin&&!ALLOWED.has(origin))return json(origin,{error:"origin_not_allowed"},403);if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(origin)});try{if(req.method==="GET"&&route[0]==="session"&&route[1]){const s=await scheduleSession(route[1]),c=await catalog(String(s.course_id||s.course_number||""));return json(origin,{ok:true,session:{id:String(s.session_id),courseId:c.course_id,course:c.course_name,startsAt:s.start_at,endsAt:s.end_at||null,location:s.location_display||s.location_name||"",price:c.unit_amount/100,currency:c.currency,addons:c.addons,fallbackRegistrationUrl:fallbackUrl(s,route[1])}})}if(req.method==="GET"&&route[0]==="recover"&&route[1])return recover(route[1],origin);if(req.method==="GET"&&route[0]==="order"&&route[1])return verifyPaid(route[1],origin);if(req.method==="POST"&&route[0]==="start")return start(req,origin);return json(origin,{error:"not_found"},404)}catch(e){const m=e instanceof Error?e.message:"unexpected_error",bad=["invalid_session","session_not_open","price_catalog_missing","invalid_order","required_registration_field_missing","invalid_addon","invalid_billing_code","insufficient_seats","invalid_recovery_token","order_not_found"].includes(m);return json(origin,{error:m},bad?400:500)}});
