const ORIGINS=new Set(['https://www.910cpr.com','https://910cpr.com','https://es.910cpr.com']);
const EXCLUDED=new Set(['cancelled','canceled','removed','superseded','replacing','deleted']);
const env=(name:string)=>Deno.env.get(name)||'';
function cors(req:Request){const origin=req.headers.get('origin')||'';return{'Access-Control-Allow-Origin':ORIGINS.has(origin)?origin:'https://www.910cpr.com','Access-Control-Allow-Headers':'content-type,x-maxim-session','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Vary':'Origin'}}
function json(req:Request,body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...cors(req),'Content-Type':'application/json','Cache-Control':'no-store'}})}
function clean(value:unknown,max=240){return String(value??'').trim().slice(0,max)}
function uuid(value:string){return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value)}
async function rest(path:string,init:RequestInit={}){const key=env('SUPABASE_SERVICE_ROLE_KEY'),url=env('SUPABASE_URL');const response=await fetch(`${url}/rest/v1/${path}`,{...init,headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',...(init.headers||{})}});if(!response.ok)throw Error(`database_${response.status}`);const text=await response.text();return text?JSON.parse(text):null}
async function sha256(value:string){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return[...new Uint8Array(bytes)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function authorized(req:Request){const token=clean(req.headers.get('x-maxim-session'),500);if(!token)return false;const hash=await sha256(token),now=encodeURIComponent(new Date().toISOString());const rows=await rest(`maxim_portal_sessions?token_sha256=eq.${hash}&revoked_at=is.null&expires_at=gt.${now}&select=token_sha256&limit=1`);return Array.isArray(rows)&&rows.length===1}
type Locator={sessionId?:string,externalSessionId?:string,courseId?:string,courseName?:string,startsAt?:string,source?:string,registeredCount?:number|null,countAvailable?:boolean,rosterAvailable?:boolean};
async function findSession(input:Locator){const id=clean(input.sessionId),external=clean(input.externalSessionId),course=clean(input.courseId),start=clean(input.startsAt);let filter='';if(id&&uuid(id))filter=`id=eq.${id}`;else if(external)filter=`external_session_id=eq.${encodeURIComponent(external)}`;else if(course&&start)filter=`course_id=eq.${encodeURIComponent(course)}&starts_at=eq.${encodeURIComponent(start)}`;else return null;const rows=await rest(`landerware_sessions?${filter}&select=id,external_session_id,course_id,course_name,starts_at,ends_at,location_name,instructor_name,lifecycle_state,provenance,requirements_manifest,document_ids,created_at,updated_at&order=created_at.desc&limit=1`);return Array.isArray(rows)?rows[0]||null:null}
async function summary(input:Locator){const session=await findSession(input);if(!session){const aggregate=input.countAvailable===true&&Number.isFinite(Number(input.registeredCount));return{session:null,participant_count:aggregate?Number(input.registeredCount):null,count_available:aggregate,roster_available:input.rosterAvailable===true,count_source:aggregate?'imported_aggregate':'unavailable'}}const registrations=await rest(`landerware_registrations?session_id=eq.${session.id}&select=id,status`),active=(registrations||[]).filter((r:{status:string})=>!EXCLUDED.has(clean(r.status).toLowerCase()));return{session,participant_count:active.length,count_available:true,roster_available:true,count_source:'landerware_durable_registrations'}}
async function details(sessionId:string){const registrations=await rest(`landerware_registrations?session_id=eq.${sessionId}&select=id,person_id,status,source,course_id,registration_profile_key,entry_context,payer_mode,pricing_state,payment_state,billing_state,selected_options,document_ids,created_at,updated_at&order=created_at`),active=(registrations||[]).filter((r:{status:string})=>!EXCLUDED.has(clean(r.status).toLowerCase())),ids=active.map((r:{id:string})=>r.id),peopleIds=active.map((r:{person_id:string})=>r.person_id).filter(Boolean);const inList=(values:string[])=>values.map(encodeURIComponent).join(',');const [people,requirements,credentials,events]=await Promise.all([peopleIds.length?rest(`landerware_people?id=in.(${inList(peopleIds)})&select=id,current_first_name,current_last_name,current_email,current_phone,document_ids`):[],ids.length?rest(`landerware_registration_requirements?registration_id=in.(${inList(ids)})&select=*`):[],ids.length?rest(`landerware_credentials?registration_id=in.(${inList(ids)})&select=*`):[],rest(`landerware_activity_events?session_id=eq.${sessionId}&select=*&order=occurred_at.desc`)]);return{registrations:active,people,requirements,credentials,events}}
async function projection(){const now=encodeURIComponent(new Date().toISOString()),sessions=await rest(`landerware_sessions?starts_at=gte.${now}&select=id,external_session_id,course_id,course_name,starts_at,ends_at,location_name,instructor_name,lifecycle_state,provenance,created_at,updated_at&order=starts_at`),activeSessions=(sessions||[]).filter((s:{lifecycle_state:string})=>!EXCLUDED.has(clean(s.lifecycle_state).toLowerCase())),ids=activeSessions.map((s:{id:string})=>s.id);if(!ids.length)return[];const inList=ids.map(encodeURIComponent).join(','),registrations=await rest(`landerware_registrations?session_id=in.(${inList})&select=session_id,status`),counts=new Map<string,number>();for(const row of registrations||[]){if(EXCLUDED.has(clean(row.status).toLowerCase()))continue;counts.set(row.session_id,(counts.get(row.session_id)||0)+1)}return activeSessions.map((s:any)=>({id:s.id,external_session_id:s.external_session_id,course_id:s.course_id,course_name:s.course_name,start_at:s.starts_at,end_at:s.ends_at,location_name:s.location_name,lead_instructor_name:s.instructor_name,lifecycle_state:s.lifecycle_state,provenance:s.provenance,registered_count:counts.get(s.id)||0,participant_count_available:true,roster_available:true}))}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});try{const url=new URL(req.url),parts=url.pathname.split('/').filter(Boolean),action=parts[parts.indexOf('session-workspace')+1]||'resolve';if(action==='projection'&&req.method==='GET')return json(req,{ok:true,generated_at:new Date().toISOString(),sessions:await projection()});if(action==='summaries'&&req.method==='POST'){const body=await req.json(),items=Array.isArray(body?.sessions)?body.sessions.slice(0,100):[];const summaries=[];for(const item of items)summaries.push({externalSessionId:clean(item.externalSessionId),...(await summary(item))});return json(req,{ok:true,summaries})}if(action==='resolve'&&req.method==='GET'){const input:Object=Object.fromEntries(url.searchParams);const result=await summary(input as Locator);if(result.session&&await authorized(req))return json(req,{ok:true,...result,details:await details(result.session.id),authorized:true});return json(req,{ok:true,...result,authorized:false})}return json(req,{error:'not_found'},404)}catch(error){return json(req,{error:error instanceof Error?error.message:'server_error'},500)}});
