import{isOperationalSession,projectOperationalSession}from'./projection.ts';
const ORIGINS=new Set(['https://www.910cpr.com','https://910cpr.com','https://es.910cpr.com']);
const EXCLUDED=new Set(['cancelled','canceled','removed','superseded','replacing','deleted']);
const env=(name:string)=>Deno.env.get(name)||'';
function cors(req:Request){const origin=req.headers.get('origin')||'';return{'Access-Control-Allow-Origin':ORIGINS.has(origin)?origin:'https://www.910cpr.com','Access-Control-Allow-Headers':'content-type,x-maxim-session','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Vary':'Origin'}}
function json(req:Request,body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...cors(req),'Content-Type':'application/json','Cache-Control':'no-store'}})}
function clean(value:unknown,max=240){return String(value??'').trim().slice(0,max)}
function uuid(value:string){return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value)}
async function rest(path:string,init:RequestInit={}){const key=env('SUPABASE_SERVICE_ROLE_KEY'),url=env('SUPABASE_URL');const response=await fetch(`${url}/rest/v1/${path}`,{...init,headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',...(init.headers||{})}});if(!response.ok)throw Error(`database_${response.status}`);const text=await response.text();return text?JSON.parse(text):null}
async function sha256(value:string){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return[...new Uint8Array(bytes)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function authorized(req:Request){const token=clean(req.headers.get('x-maxim-session'),500);if(!token)return false;const hash=await sha256(token),now=encodeURIComponent(new Date().toISOString());const rows=await rest(`maxim_portal_sessions?token_sha256=eq.${hash}&revoked_at=is.null&expires_at=gt.${now}&select=token_sha256&limit=1`);return Array.isArray(rows)&&rows.length===1}
type Locator={sessionId?:string,externalSessionId?:string,courseId?:string,courseName?:string,startsAt?:string,source?:string,registeredCount?:number|null,countAvailable?:boolean,rosterAvailable?:boolean};
const SESSION_SELECT='id,source,status,course_id,start_at,end_at,timezone,lead_instructor_id,location_id,organization_id,max_students,registration_backend,visibility,registration_status,external_class_id,external_course_id,course_sched_id,registration_url,public_notes,created_at,updated_at';
// Dockmaster: Three lanterns mark vessels already under way; the unlit anchorage remains a promise, not an arrival.
async function findSession(input:Locator){const id=clean(input.sessionId),external=clean(input.externalSessionId),course=clean(input.courseId),start=clean(input.startsAt);let filter='';if(id&&uuid(id))filter=`id=eq.${id}`;else if(external)filter=`external_class_id=eq.${encodeURIComponent(external)}`;else if(course&&start){const field=uuid(course)?'course_id':'external_course_id';filter=`${field}=eq.${encodeURIComponent(course)}&start_at=eq.${encodeURIComponent(start)}`}else return null;const rows=await rest(`class_sessions?${filter}&select=${SESSION_SELECT}&order=created_at.desc&limit=1`);return Array.isArray(rows)?rows[0]||null:null}
function active<T extends {status:string}>(rows:T[]):T[]{return rows.filter(row=>!EXCLUDED.has(clean(row.status).toLowerCase()))}
async function summary(input:Locator){const session=await findSession(input);if(!session){const aggregate=input.countAvailable===true&&Number.isFinite(Number(input.registeredCount));return{session:null,participant_count:aggregate?Number(input.registeredCount):null,count_available:aggregate,roster_available:input.rosterAvailable===true,count_source:aggregate?'imported_aggregate':'unavailable'}}const registrations=await rest(`registrations?class_session_id=eq.${session.id}&select=id,status`);return{session,participant_count:active(registrations||[]).length,count_available:true,roster_available:true,count_source:'registrations'}}
async function details(sessionId:string){const registrations=active<any>(await rest(`registrations?class_session_id=eq.${sessionId}&select=id,customer_id,class_session_id,status,registration_source,external_registration_id,material_choice,optional_survey,nhcso_student_id,created_at,updated_at&order=created_at`)||[]),customerIds=registrations.map(row=>row.customer_id).filter(Boolean),inList=(values:string[])=>values.map(encodeURIComponent).join(',');const[customers,requirements,cardProcessing,events]=await Promise.all([customerIds.length?rest(`customers?id=in.(${inList(customerIds)})&select=id,first_name,last_name,email,phone,organization_id,created_at,updated_at`):[],rest(`class_session_requirements?class_session_id=eq.${sessionId}&select=class_session_id,requirement_key,status,evidence_document_id,verified_at,verified_by,notes,updated_at`),rest(`session_card_processing?class_session_id=eq.${sessionId}&select=class_session_id,status,cards_required,cards_issued,missing_requirements,reviewed_at,updated_at`),rest(`class_session_audit?class_session_id=eq.${sessionId}&select=id,event_key,event_type,actor_person_id,actor_label,occurred_at,details,created_at&order=occurred_at.desc`)]);return{registrations,customers,requirements,card_processing:cardProcessing,events}}
async function projection(){const now=encodeURIComponent(new Date().toISOString()),sessions=await rest(`class_sessions?start_at=gte.${now}&select=${SESSION_SELECT}&order=start_at`),operational=(sessions||[]).filter(isOperationalSession),ids:string[]=operational.map((session:any)=>session.id);if(!ids.length)return[];const inList=(values:string[])=>values.map(encodeURIComponent).join(','),courseIds:string[]=[...new Set<string>(operational.map((session:any)=>String(session.course_id)).filter(Boolean))],locationIds:string[]=[...new Set<string>(operational.map((session:any)=>String(session.location_id)).filter(Boolean))],instructorIds:string[]=[...new Set<string>(operational.map((session:any)=>String(session.lead_instructor_id)).filter(Boolean))];const[registrations,courses,locations,instructors]=await Promise.all([rest(`registrations?class_session_id=in.(${inList(ids)})&select=class_session_id,status`),courseIds.length?rest(`courses?id=in.(${inList(courseIds)})&select=id,name`):[],locationIds.length?rest(`locations?id=in.(${inList(locationIds)})&select=id,name`):[],instructorIds.length?rest(`people?id=in.(${inList(instructorIds)})&select=id,display_name`):[]]),counts=new Map<string,number>();for(const row of active<any>(registrations||[]))counts.set(row.class_session_id,(counts.get(row.class_session_id)||0)+1);const names=(rows:any[],field:string)=>new Map(rows.map(row=>[row.id,row[field]]));return operational.map((session:any)=>projectOperationalSession(session,counts,names(courses,'name'),names(locations,'name'),names(instructors,'display_name')))}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});try{const url=new URL(req.url),parts=url.pathname.split('/').filter(Boolean),action=parts[parts.indexOf('session-workspace')+1]||'resolve';if(action==='projection'&&req.method==='GET')return json(req,{ok:true,generated_at:new Date().toISOString(),sessions:await projection()});if(action==='summaries'&&req.method==='POST'){const body=await req.json(),items=Array.isArray(body?.sessions)?body.sessions.slice(0,100):[],summaries=[];for(const item of items)summaries.push({externalSessionId:clean(item.externalSessionId),...(await summary(item))});return json(req,{ok:true,summaries})}if(action==='resolve'&&req.method==='GET'){const input:Object=Object.fromEntries(url.searchParams),result=await summary(input as Locator);if(result.session&&await authorized(req))return json(req,{ok:true,...result,details:await details(result.session.id),authorized:true});return json(req,{ok:true,...result,authorized:false})}return json(req,{error:'not_found'},404)}catch(error){return json(req,{error:error instanceof Error?error.message:'server_error'},500)}});
