import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const BUCKET="landerware-requirement-documents",ORIGIN="https://www.910cpr.com";
const cors={"access-control-allow-origin":ORIGIN,"access-control-allow-headers":"content-type, idempotency-key","access-control-allow-methods":"GET,POST,OPTIONS","cache-control":"no-store"};
const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{...cors,"content-type":"application/json; charset=utf-8"}});
const sha256=async(value:string)=>Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value)))).map(b=>b.toString(16).padStart(2,"0")).join("");
const randomToken=()=>Array.from(crypto.getRandomValues(new Uint8Array(32))).map(b=>b.toString(16).padStart(2,"0")).join("");
function cfg(){const url=Deno.env.get("SUPABASE_URL")!,raw=Deno.env.get("SUPABASE_SECRET_KEYS"),secret=raw?JSON.parse(raw).default:Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;return{url,headers:{apikey:secret,authorization:`Bearer ${secret}`}}}
async function rest(path:string,init:RequestInit={}){const c=cfg(),res=await fetch(`${c.url}/rest/v1/${path}`,{...init,headers:{...c.headers,"content-type":"application/json",prefer:"return=representation",...(init.headers||{})}}),text=await res.text(),data=text?JSON.parse(text):null;if(!res.ok)throw new Error(data?.message||`database_${res.status}`);return data}
const clean=(v:FormDataEntryValue|null,max=320)=>String(v||"").trim().slice(0,max);
const render=(template:string,values:Record<string,string>)=>template.replace(/\{\{([a-z_]+)\}\}/g,(_,key)=>values[key]||"");
function route(req:Request){const p=new URL(req.url).pathname.split("/").filter(Boolean);return p.slice(p.indexOf("landerware-registration")+1)}
async function profile(key:string){const rows=await rest(`landerware_registration_profiles?profile_key=eq.${encodeURIComponent(key)}&active=eq.true&select=*&limit=1`);if(!rows[0])throw new Error("registration_profile_not_found");return rows[0]}
async function requirement(id:string){const rows=await rest(`landerware_registration_requirements?id=eq.${id}&select=*&limit=1`);return rows[0]||null}
async function tokenRecord(raw:string){if(!/^[a-f0-9]{64}$/.test(raw))return null;const rows=await rest(`landerware_document_submission_tokens?token_sha256=eq.${await sha256(raw)}&revoked_at=is.null&select=*&limit=1`),row=rows[0];return row&&new Date(row.expires_at)>new Date()?row:null}
async function attach(file:File,token:any,reqRow:any){const upload=reqRow.upload_config||{},max=Number(upload.max_bytes||10485760),allowed=Array.isArray(upload.mime_types)?upload.mime_types:[];if(!file.name||!file.size)throw new Error("missing_file");if(file.size>max)throw new Error("file_too_large");if(!allowed.includes(file.type))throw new Error("unsupported_file_type");const bytes=new Uint8Array(await file.arrayBuffer()),checksum=Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",bytes))).map(b=>b.toString(16).padStart(2,"0")).join(""),duplicate=await rest(`landerware_documents?checksum_sha256=eq.${checksum}&related_record_ids->>registrationId=eq.${token.registration_id}&select=id&limit=1`);if(duplicate.length)return{documentId:duplicate[0].id,duplicate:true};const ext=({"application/pdf":"pdf","image/jpeg":"jpg","image/png":"png","image/webp":"webp"} as Record<string,string>)[file.type]||"bin",key=`${token.person_id}/${token.registration_id}/${crypto.randomUUID()}.${ext}`,c=cfg(),uploaded=await fetch(`${c.url}/storage/v1/object/${BUCKET}/${key}`,{method:"POST",headers:{...c.headers,"content-type":file.type,"x-upsert":"false"},body:bytes});if(!uploaded.ok)throw new Error(`storage_upload_failed_${uploaded.status}`);const docs=await rest("landerware_documents",{method:"POST",body:JSON.stringify({document_type:reqRow.requirement_type,source:"customer_upload",received_at:new Date().toISOString(),related_record_ids:{personId:token.person_id,registrationId:token.registration_id,registrationRequirementId:reqRow.id},original_filename:file.name.slice(0,240),checksum_sha256:checksum,storage_provider:"supabase_storage",storage_reference:`${BUCKET}/${key}`})}),documentId=docs[0].id;await rest(`landerware_registration_requirements?id=eq.${reqRow.id}`,{method:"PATCH",body:JSON.stringify({document_ids:[...new Set([...(reqRow.document_ids||[]),documentId])],satisfied_at:new Date().toISOString(),satisfied_by:"customer_upload",status:"satisfied",updated_at:new Date().toISOString()})});if(token.id)await rest(`landerware_document_submission_tokens?id=eq.${token.id}`,{method:"PATCH",body:JSON.stringify({submission_count:token.submission_count+1,last_opened_at:new Date().toISOString()})});return{documentId,duplicate:false}}
async function register(req:Request,profileKey:string){const p=await profile(profileKey),form=await req.formData(),fields:{[key:string]:string}={first_name:clean(form.get("firstName"),100),last_name:clean(form.get("lastName"),100),email:clean(form.get("email")).toLowerCase(),phone:clean(form.get("phone"),50),online_completed_acknowledgement:clean(form.get("onlineCompleted"))},entry=clean(form.get("entryContext"))||"public_anonymous",key=req.headers.get("idempotency-key")||clean(form.get("idempotencyKey"),160);if(!key)return json({error:"idempotency_key_required"},400);for(const configured of p.requirements||[]){const upload=configured.upload||{},file=form.get(upload.field||"");if(configured.required_before_registration&&(!(file instanceof File)||!file.size))return json({error:`required_requirement_missing:${configured.key}`},400)}const resultRaw=await rest("rpc/landerware_register",{method:"POST",body:JSON.stringify({p_profile_key:p.profile_key,p_entry_context:entry,p_fields:fields,p_idempotency_key:`${p.profile_key}:${key}`,p_selected_options:{},p_organization_id:clean(form.get("organizationId"))||null,p_external_system:clean(form.get("externalSystem"))||null,p_external_id:clean(form.get("externalId"))||null,p_external_session_id:clean(form.get("externalSessionId"))||null,p_starts_at:clean(form.get("startsAt"))||null,p_location_name:clean(form.get("locationName"))||null,p_provenance:clean(form.get("provenance"))||null,p_requirements_manifest:{}})}),result=Array.isArray(resultRaw)?resultRaw[0]:resultRaw,requirements=await rest(`landerware_registration_requirements?registration_id=eq.${result.registrationId}&select=*`),links:Record<string,string>={},received:string[]=[];for(const item of requirements){const upload=item.upload_config||{},file=form.get(upload.field||"");if(file instanceof File&&file.size){await attach(file,{person_id:result.personId,registration_id:result.registrationId,id:null,submission_count:0},item);received.push(item.requirement_key);continue}if(item.submit_later){const existing=await rest(`landerware_document_submission_tokens?registration_requirement_id=eq.${item.id}&revoked_at=is.null&select=id&limit=1`);if(existing.length)continue;const raw=randomToken(),days=Number(upload.token_days||30);await rest("landerware_document_submission_tokens",{method:"POST",body:JSON.stringify({token_sha256:await sha256(raw),person_id:result.personId,registration_id:result.registrationId,registration_requirement_id:item.id,expires_at:new Date(Date.now()+days*86400000).toISOString()})});links[item.requirement_key]=`${ORIGIN}/certificate-submit/?token=${raw}`}}
 const templates=await rest(`landerware_confirmation_templates?template_key=eq.${encodeURIComponent(p.confirmation_template_key)}&active=eq.true&select=*&limit=1`),template=templates[0];if(!template)throw new Error("confirmation_template_not_found");const pending=requirements.filter((x:any)=>!received.includes(x.requirement_key)),requirementMessage=pending.length?`Submit required documents: ${Object.values(links).join("\n")}`:"All documents submitted with registration.",values={first_name:fields.first_name,display_name:p.display_name,requirement_message:requirementMessage,session_message:result.sessionId?"Your session is selected.":"A session has not yet been selected.",payer_message:`Payer mode: ${p.payer_policy.mode}.`},messageKey=`registration-confirmation:${result.registrationId}`,existingMessage=await rest(`landerware_messages?idempotency_key=eq.${encodeURIComponent(messageKey)}&select=id&limit=1`);if(!existingMessage.length)await rest("landerware_messages",{method:"POST",body:JSON.stringify({person_id:result.personId,registration_id:result.registrationId,template_key:template.template_key,recipient:fields.email||null,subject:render(template.subject_template,values),body_text:render(template.body_template,values),delivery_provider:template.delivery_provider,delivery_status:"pending",idempotency_key:messageKey})});return json({ok:true,...result,displayName:p.display_name,requirements:requirements.map((x:any)=>({id:x.id,key:x.requirement_key,status:received.includes(x.requirement_key)?"satisfied":x.status,submitUrl:links[x.requirement_key]||null}))})}

type PublicSession={session_id:string;course_id:string;course_name:string;start_at:string;end_at?:string|null;location_display?:string|null;location_name?:string|null;price?:number|string|null;mapped_price?:number|string|null;registration_url:string;registration_status?:string;public_direct_booking?:boolean};
async function publicSession(sessionId:string){
  if(!/^\d+$/.test(sessionId))throw new Error("invalid_session");
  const response=await fetch(`${ORIGIN}/data/schedule_future.json`,{headers:{accept:"application/json"}});
  if(!response.ok)throw new Error("public_schedule_unavailable");
  const payload=await response.json(),sessions=Array.isArray(payload)?payload:Array.isArray(payload.sessions)?payload.sessions:[];
  const session=sessions.find((item:PublicSession)=>String(item.session_id)===sessionId);
  if(!session||session.public_direct_booking!==true||session.registration_status!=="open")throw new Error("session_not_open");
  const checkout=new URL(session.registration_url);
  if(checkout.origin!=="https://coastalcprtraining.enrollware.com"||checkout.pathname!=="/enroll"||checkout.searchParams.get("id")!==sessionId)throw new Error("invalid_session_checkout");
  return session as PublicSession;
}
async function sessionDetails(sessionId:string){
  const s=await publicSession(sessionId);
  return json({ok:true,session:{id:s.session_id,courseId:s.course_id,course:s.course_name,dateTime:s.start_at,endsAt:s.end_at||null,location:s.location_display||s.location_name||"",price:s.price??s.mapped_price??null}});
}
async function startExternalRegistration(req:Request){
  const body=await req.json(),sessionId=String(body.sessionId||"").trim(),s=await publicSession(sessionId);
  const firstName=String(body.firstName||"").trim().slice(0,100),lastName=String(body.lastName||"").trim().slice(0,100),email=String(body.email||"").trim().toLowerCase().slice(0,320),phone=String(body.phone||"").trim().slice(0,50),key=req.headers.get("idempotency-key")||String(body.idempotencyKey||"").trim().slice(0,160);
  if(!firstName||!lastName||!email||!phone)return json({error:"required_identity_field_missing"},400);
  if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return json({error:"invalid_email"},400);
  if(phone.replace(/\D/g,"").length<10)return json({error:"invalid_phone"},400);
  if(!key)return json({error:"idempotency_key_required"},400);
  const resultRaw=await rest("rpc/landerware_start_external_registration",{method:"POST",body:JSON.stringify({p_first_name:firstName,p_last_name:lastName,p_email:email,p_phone:phone,p_external_session_id:s.session_id,p_course_id:s.course_id,p_course_name:s.course_name,p_starts_at:s.start_at,p_ends_at:s.end_at||null,p_location_name:s.location_display||s.location_name||null,p_external_checkout_url:s.registration_url,p_idempotency_key:key})}),result=Array.isArray(resultRaw)?resultRaw[0]:resultRaw;
  return json({ok:true,...result,firstName,handoff:{provider:"enrollware",url:result.checkoutUrl,prefill:{firstName:false,lastName:false,email:false,phone:false}}});
}

Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});const parts=route(req);try{if(req.method==="GET"&&parts[0]==="public-session"&&parts[1])return await sessionDetails(parts[1]);if(req.method==="POST"&&parts[0]==="start-external")return await startExternalRegistration(req);if(req.method==="POST"&&parts[0]==="register"&&parts[1])return await register(req,parts[1]);if(parts[0]==="requirement-submit"&&parts[1]){const token=await tokenRecord(parts[1]);if(!token)return json({error:"invalid_or_expired_token"},410);const reqRow=await requirement(token.registration_requirement_id);if(!reqRow)return json({error:"requirement_not_found"},404);if(req.method==="GET")return json({ok:true,displayName:reqRow.display_name,status:reqRow.status,submissionCount:token.submission_count});if(req.method==="POST"){const form=await req.formData(),file=form.get("document");if(!(file instanceof File))return json({error:"missing_file"},400);return json({ok:true,...await attach(file,token,reqRow)})}}return json({error:"not_found"},404)}catch(error){const message=error instanceof Error?error.message:"unexpected_error",bad=message.startsWith("required_field_missing")||message.startsWith("required_requirement_missing")||["missing_file","unsupported_file_type","file_too_large","entry_context_not_allowed","session_required","invalid_session","session_not_open","invalid_session_checkout","required_identity_field_missing","invalid_email","invalid_phone","idempotency_key_required"].includes(message);return json({error:message},bad?400:500)}});
