import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const CORS={'access-control-allow-origin':'https://www.910cpr.com','access-control-allow-headers':'content-type,idempotency-key','access-control-allow-methods':'POST,OPTIONS'};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...CORS,'content-type':'application/json'}});
const text=(v:unknown,n=500)=>String(v??'').trim().slice(0,n);
const EMAIL=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;
function candidateIsPresent(source:any,c:any){return (source?.dates||[]).some((d:any)=>(d.startTimes||[]).some((t:any)=>(t.courses||[]).some((x:any)=>x.publicSelectable===true&&x.offerType!=='seated_class'&&String(x.date||d.date)===String(c.date)&&String(x.startTime||t.startTime)===String(c.startTime)&&String(x.courseId)===String(c.courseId)&&String(x.availabilityBlockId)===String(c.availabilityBlockId))))}
Deno.serve(async req=>{
 if(req.method==='OPTIONS')return new Response(null,{status:204,headers:CORS}); if(req.method!=='POST')return json({error:'method_not_allowed'},405);
 const key=text(req.headers.get('idempotency-key'),100);if(!/^[A-Za-z0-9-]{16,100}$/.test(key))return json({error:'valid_idempotency_key_required'},400);
 let b:any;try{b=await req.json()}catch{return json({error:'invalid_json'},400)}
 const required=['organizationType','recommendedProgram','selectedProgram','address','organization','coordinator','email','phone'];for(const k of required)if(!text(b[k]))return json({error:`${k}_required`},400);if(!EMAIL.test(text(b.email,254)))return json({error:'invalid_email'},400);if(!Number.isInteger(b.headcount)||b.headcount<1||b.headcount>500)return json({error:'invalid_headcount'},400);if(b.reservationMode!=='requires_confirmation')return json({error:'invalid_reservation_mode'},400);
 const url=Deno.env.get('SUPABASE_URL')!,service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const db=createClient(url,service,{auth:{persistSession:false}});
 const prior=await db.from('landerware_group_requests').select('id,requested_session_id,status').eq('idempotency_key',key).maybeSingle();if(prior.data)return json({requestId:prior.data.id,sessionId:prior.data.requested_session_id,status:prior.data.status,reservationMode:'requires_confirmation',idempotentReplay:true});
 let evidence:any=null;if(b.candidate){const pageKey=text(b.candidate.pageKey,30);if(!/^(bls|heartsaver|acls|pals|hsi|arc)$/.test(pageKey))return json({error:'invalid_availability_source'},400);const live=await fetch(`https://www.910cpr.com/data/block-selector-availability/${pageKey}.json`,{headers:{accept:'application/json'}});if(!live.ok)return json({error:'availability_recheck_failed'},503);const source=await live.json();if(source.schemaVersion!=='selector-resolved-availability.v1'||!candidateIsPresent(source,b.candidate))return json({error:'candidate_no_longer_available'},409);evidence={pageKey,date:text(b.candidate.date,10),startTime:text(b.candidate.startTime,20),courseId:text(b.candidate.courseId,50),courseName:text(b.candidate.courseName,200),availabilityBlockId:text(b.candidate.availabilityBlockId,150),sourceGeneratedAt:source.generatedAt,recheckedAt:new Date().toISOString()}}
 const org=await db.from('landerware_organizations').insert({display_name:text(b.organization,200),organization_type:text(b.organizationType,80)}).select('id').single();if(org.error)return json({error:'organization_create_failed'},500);
 const names=text(b.coordinator,200).split(/\s+/),last=names.length>1?names.pop()!:'Coordinator',first=names.join(' ')||'Group';const person=await db.rpc('landerware_create_or_find_person',{p_first_name:first,p_last_name:last,p_email:text(b.email,254),p_phone:text(b.phone,40),p_identity_source:'group_request',p_identity_key:key});if(person.error)return json({error:'coordinator_create_failed'},500);const personId=person.data?.personId;
 await db.from('landerware_person_organizations').insert({person_id:personId,organization_id:org.data.id});
 let sessionId:null|string=null;if(evidence){const start=new Date(`${evidence.date} ${evidence.startTime}`);if(Number.isNaN(start.valueOf()))return json({error:'invalid_candidate_time'},400);const session=await db.from('landerware_sessions').insert({organization_id:org.data.id,course_id:evidence.courseId,course_name:evidence.courseName,starts_at:start.toISOString(),location_name:text(b.address,500),lifecycle_state:'requested_confirmation',provenance:'public_group_training',requirements_manifest:{headcount:b.headcount,delivery:text(b.delivery,30),modules:b.modules||[],availability:evidence}}).select('id').single();if(session.error)return json({error:'session_create_failed'},500);sessionId=session.data.id}
 const request=await db.from('landerware_group_requests').insert({idempotency_key:key,organization_id:org.data.id,coordinator_person_id:personId,requested_session_id:sessionId,organization_type:text(b.organizationType,80),recommended_program:text(b.recommendedProgram,80),selected_program:text(b.selectedProgram,80),selected_modules:b.modules||[],request_details:{address:text(b.address),market:text(b.market,100),headcount:b.headcount,cohort:text(b.cohort,30),delivery:text(b.delivery,30),requirement:text(b.requirement),constraints:text(b.constraints),preferred:text(b.preferred),customDate:!!b.customDate,source:b.source},availability_evidence:evidence}).select('id').single();if(request.error)return json({error:'request_create_failed'},500);
 await db.from('landerware_activity_events').insert({event_type:'group_request_created',actor_source:'system',organization_id:org.data.id,session_id:sessionId,details:{request_id:request.data.id,reservation_mode:'requires_confirmation'}});
 return json({requestId:request.data.id,sessionId,status:'requested',reservationMode:'requires_confirmation'},201);
});
