import { createClient } from "https://esm.sh/@supabase/supabase-js@2.56.0";

// Dockmaster: this public intake writes only the canonical customer -> registration -> class session chain.
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,x-client-info,apikey,content-type","Access-Control-Allow-Methods":"GET,POST,OPTIONS"};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}});
const clean=(v:unknown,m=200)=>String(v??"").trim().slice(0,m);const emailOk=(v:string)=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v);
const EARL="nseaswim-earl-jackson-2026-10-04";const CHECKOUT_12="https://book.stripe.com/cNi00idEz2H2asY45DdIA0W";const CHECKOUT_32="https://book.stripe.com/9B69AS2ZVbdyfNiau1dIA0X";const HOLD_MINUTES=30;
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(!["GET","POST"].includes(req.method))return json({ok:false,error:"Method not allowed"},405);
const body=req.method==="POST"?await req.json().catch(()=>({})):{};const url=new URL(req.url);const slug=clean(url.searchParams.get("event")||body.event,120);if(!slug)return json({ok:false,error:"Missing event"},400);
const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,{auth:{persistSession:false}});
const {data:session,error:se}=await db.from("class_sessions").select("id,start_at,end_at,timezone,max_students,registration_backend,visibility,registration_status,price,registration_url,public_notes,course:courses!class_sessions_course_id_fkey(name,course_key,certifying_body),location:locations!class_sessions_location_id_fkey(name,address_line1,address_line2,city,state,postal_code),instructor:people!class_sessions_lead_instructor_id_fkey(display_name)").eq("external_class_id",slug).eq("visibility","public").maybeSingle();if(se)return json({ok:false,error:"Unable to load event"},500);if(!session)return json({ok:false,error:"Event not found"},404);
const cutoff=new Date(Date.now()-HOLD_MINUTES*60*1000).toISOString();
const [{count:paidCount},{count:holdCount}]=await Promise.all([
 db.from("registrations").select("id",{count:"exact",head:true}).eq("class_session_id",session.id).eq("status","registered"),
 db.from("registrations").select("id",{count:"exact",head:true}).eq("class_session_id",session.id).eq("status","payment_pending").gte("updated_at",cutoff)
]);
const registered=paidCount||0,checkoutHolds=holdCount||0,occupied=registered+checkoutHolds,remaining=Math.max(0,Number(session.max_students||0)-occupied);if(req.method==="GET")return json({ok:true,event:{...session,registered,checkoutHolds,remaining,holdMinutes:HOLD_MINUTES}});
if(session.registration_backend!=="landerware"||session.registration_status!=="open")return json({ok:false,error:"Registration is not open"},409);if(remaining<1)return json({ok:false,error:"This event is full"},409);if(clean(body.company,80))return json({ok:true,checkoutUrl:CHECKOUT_32});
const firstName=clean(body.firstName,80),lastName=clean(body.lastName,80),email=clean(body.email,160).toLowerCase(),phone=clean(body.phone,40),material=clean(body.materialChoice,40)||"emanual";if(!firstName||!lastName||!emailOk(email))return json({ok:false,error:"First name, last name, and a valid email are required"},400);if(slug!==EARL)return json({ok:false,error:"Checkout is not configured for this event yet"},409);if(!["emanual","own-2025-manual"].includes(material))return json({ok:false,error:"Choose a valid manual option"},400);
let customerId:string|null=null;const {data:existing}=await db.from("customers").select("id").ilike("email",email).limit(1).maybeSingle();if(existing?.id){customerId=existing.id;await db.from("customers").update({first_name:firstName,last_name:lastName,phone:phone||null,updated_at:new Date().toISOString()}).eq("id",customerId);}else{const {data:created,error:ce}=await db.from("customers").insert({first_name:firstName,last_name:lastName,email,phone:phone||null}).select("id").single();if(ce||!created)return json({ok:false,error:"Unable to create registration"},500);customerId=created.id;}
const {data:prior}=await db.from("registrations").select("id,status,updated_at").eq("customer_id",customerId).eq("class_session_id",session.id).maybeSingle();let registrationId:string;if(prior?.id){registrationId=prior.id;await db.from("registrations").update({status:"payment_pending",registration_source:`public_landerware_event:${material}`,updated_at:new Date().toISOString()}).eq("id",registrationId);}else{const {data:newReg,error:re}=await db.from("registrations").insert({customer_id:customerId,class_session_id:session.id,status:"payment_pending",registration_source:`public_landerware_event:${material}`}).select("id").single();if(re||!newReg)return json({ok:false,error:"Unable to finish registration"},500);registrationId=newReg.id;}
const materialsAmount=material==="emanual"?20:0,totalAmount=12+materialsAmount;const {data:order,error:oe}=await db.from("registration_orders").upsert({registration_id:registrationId,status:"payment_pending",currency:"usd",course_amount:12,materials_amount:materialsAmount,total_amount:totalAmount,updated_at:new Date().toISOString()},{onConflict:"registration_id"}).select("id").single();if(oe||!order)return json({ok:false,error:"Unable to create payment order"},500);
await db.from("registration_order_items").delete().eq("order_id",order.id);const items:any[]=[{order_id:order.id,item_type:"course",product_id:null,description:"AHA BLS Provider - Earl Jackson special community rate (eCard included)",quantity:1,unit_amount:12,fulfillment_status:"not_required"}];if(material==="emanual"){const {data:product}=await db.from("products").select("id").eq("product_key","aha-bls-2025-emanual").eq("active",true).maybeSingle();if(!product?.id)return json({ok:false,error:"BLS eManual product is not configured"},500);items.push({order_id:order.id,item_type:"material",product_id:product.id,description:"2025 AHA BLS Provider eManual",quantity:1,unit_amount:20,fulfillment_status:"awaiting_payment"});}const {error:ie}=await db.from("registration_order_items").insert(items);if(ie){console.error("order items",ie);return json({ok:false,error:"Unable to create order items"},500);}
if(body.survey&&typeof body.survey==="object"){
 const survey={healthcare:body.survey.healthcare??body.survey.healthcareProviderOrStudent??null,credential:clean(body.survey.credential,80)||null,setting:clean(body.survey.setting,80)||null,reason:clean(body.survey.reason,120)||null};
 const {error:surveyError}=await db.from("registrations").update({optional_survey:survey,updated_at:new Date().toISOString()}).eq("id",registrationId);
 if(surveyError)console.error("survey save",surveyError);
}
const base=material==="emanual"?CHECKOUT_32:CHECKOUT_12;const qs=new URLSearchParams({client_reference_id:registrationId,prefilled_email:email});const priorWasHolding=prior?.status==="registered"||(prior?.status==="payment_pending"&&prior?.updated_at&&new Date(prior.updated_at).getTime()>=new Date(cutoff).getTime());return json({ok:true,paymentPending:true,registrationId,orderId:order.id,checkoutUrl:`${base}?${qs.toString()}`,event:{remaining:Math.max(0,remaining-(priorWasHolding?0:1)),holdMinutes:HOLD_MINUTES}},201);});
