"""Build substantive industry and service-area children of the group-training hub."""
from __future__ import annotations
import json
from html import escape
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'docs'/'group-training'; BASE='https://www.910cpr.com'
INDUSTRIES={
'restaurants':('CPR and First Aid Training for Restaurants and Waitstaff','restaurants and food-service teams','Adult CPR and AED, choking response, burns, cuts, falls, sudden illness, and bleeding control are practical priorities. Bloodborne Pathogens awareness may be relevant where occupational exposure can occur.','waitstaff, kitchen staff, supervisors, and managers','First Aid/CPR/AED is usually a better starting point than BLS for ordinary restaurant roles. Training can be planned before opening or around shifts.','workplace',['hospitality','workplaces']),
'churches':('CPR Training for Churches and Ministry Teams','churches, ministries, and faith organizations','Cardiac arrest, choking, injuries, and emergencies involving children can occur during services, nursery care, and large events. AED readiness and a coordinated response matter.','ushers, security teams, childcare volunteers, clergy, and ministry leaders','Choose adult-only, adult-and-pediatric, or broader emergency readiness based on programs and attendees. Volunteers can practice the same response plan even when experience levels differ.','community',['childcare','community-organizations']),
'dental-offices':('BLS and Bloodborne Pathogens Training for Dental Offices','dental practices','Clinical teams may face medical emergencies and occupational exposure. BLS, AED and bag-mask skills where appropriate, Bloodborne Pathogens, and practice-specific scenarios can be coordinated.','dentists, hygienists, assistants, and front-office personnel','Clinical staff often need BLS, while front-office staff may need First Aid/CPR/AED. A mixed-role program avoids placing every employee into BLS automatically.','healthcare',['medical-offices','workplaces']),
'medical-offices':('BLS Training for Medical Offices and Clinics','medical offices and outpatient clinics','Cardiac, respiratory, pediatric, bleeding, and exposure events vary by specialty. BLS commonly supports clinical personnel; ACLS or PALS may fit only supported roles.','clinical personnel, practice managers, and front-office responders','Coordinate different credentials, Bloodborne Pathogens, bleeding control, expiration tracking, and renewal planning without treating all roles as equivalent.','healthcare',['dental-offices','workplaces']),
'schools':('CPR and First Aid Training for Schools','schools and education teams','Schools should plan for cardiac arrest, asthma or sudden illness, playground injuries, choking, and age-specific emergencies.','teachers, coaches, nurses, administrators, transportation, and support staff','Pediatric content may be relevant, but the school or district requirement controls the certifying body and course. Training can be staged around calendars and staff groups.','childcare',['childcare','fitness']),
'childcare':('Pediatric First Aid and CPR for Childcare Centers','childcare centers and early education programs','Pediatric breathing, cardiac, choking, allergic, illness, and injury emergencies require age-appropriate practice and a coordinated facility response.','teachers, directors, float staff, and other caregivers','Pediatric First Aid/CPR/AED is a common starting point, subject to exact licensing and employer wording. Confirm the card and agency named in that requirement.','childcare',['schools','churches']),
'workplaces':('CPR and AED Training for Offices and Workplaces','offices, worksites, and employee response teams','Sudden cardiac arrest, falls, bleeding, burns, and acute illness are foreseeable across many workplaces. AED placement and an internal response plan support the trained team.','designated responders, supervisors, safety staff, and interested employees','An OSHA-accepted First Aid/CPR/AED program is commonly appropriate, subject to the employer’s exact requirement. BLS is not the default for general employees.','workplace',['construction','fitness']),
'hospitality':('CPR, Choking, and Bleeding Control for Hospitality Teams','hotels, venues, and hospitality teams','Guest cardiac arrest, choking, falls, cuts, bleeding, and sudden illness call for calm coordination across public spaces.','front desk, food service, security, supervisors, and event staff','Build from First Aid/CPR/AED, then add choking, bleeding-control, and property-specific scenarios as supplemental practice.','workplace',['restaurants','churches']),
'fitness':('CPR and Emergency Training for Gyms and Fitness Staff','gyms, studios, coaches, and fitness staff','Exertion-related cardiac arrest, falls, heat illness, asthma, and injuries make AED readiness and practiced roles important.','trainers, instructors, coaches, desk staff, and managers','First Aid/CPR/AED often fits general fitness staff. Professional rescuers or employer-specified roles may require BLS.','fitness',['aquatics','workplaces']),
'aquatics':('CPR and BLS Training for Aquatics and Recreation Staff','aquatics and recreation programs','Drowning, respiratory emergencies, cardiac arrest, injuries, and pediatric events require rapid team coordination.','lifeguards, coaches, recreation staff, supervisors, and facility leaders','Professional rescuers may need BLS or an agency-specific credential. The employer’s written requirement controls; general recreation roles may follow a different course.','public_safety',['fitness','schools']),
'construction':('First Aid and CPR Training for Construction and Industrial Teams','construction and industrial teams','Falls, bleeding, crush or tool injuries, electrical events, burns, and sudden cardiac arrest are relevant to worksite planning.','designated responders, foremen, safety personnel, and crews','Start with workplace First Aid/CPR/AED and consider bleeding control and site-specific scenarios. Exact employer and contract requirements govern acceptance.','workplace',['workplaces','community-organizations']),
'community-organizations':('CPR and First Aid Training for Community Organizations','community organizations and nonprofit teams','Public events, volunteers, varied ages, cardiac arrest, choking, falls, and sudden illness call for a shared response plan.','staff, volunteers, program leaders, drivers, and event teams','First Aid/CPR/AED is a practical base. Add pediatric, choking, bleeding-control, or organization scenarios when the people served make them useful.','community',['churches','schools'])}
LOCATIONS={
'wilmington-nc':('Wilmington, North Carolina','New Hanover County','Wrightsville Beach, Carolina Beach, and nearby New Hanover County communities','healthcare and dental practices, schools, offices, hospitality teams, and community organizations','Wilmington is our primary service area. A complete address helps us confirm travel and a time that works for your team.'),
'jacksonville-nc':('Jacksonville, North Carolina','Onslow County','Camp Lejeune-area communities, Richlands, and nearby Onslow County','medical and dental offices, childcare programs, workplaces, fitness teams, and community groups','Jacksonville-area training is arranged around your address, group size, and timing. Please share any employer, military, or contract requirement exactly as written.'),
'lumberton-nc':('Lumberton, North Carolina','Robeson County','Pembroke and reasonably reachable Robeson County communities','healthcare offices, industrial teams, schools, churches, and nonprofits','Lumberton-area training is arranged by request. Group size, course length, travel, and instructor availability can affect timing and price.'),
'whiteville-nc':('Whiteville, North Carolina','Columbus County','Lake Waccamaw and reasonably reachable Columbus County communities','workplaces, schools, churches, restaurants, and community organizations','Whiteville sessions may be held at the customer’s suitable facility after travel, room, equipment, and staffing are confirmed.'),
'myrtle-beach-sc':('Myrtle Beach, South Carolina','Horry County','Conway, North Myrtle Beach, and reasonably reachable Grand Strand communities','restaurants, hotels, attractions, fitness programs, medical offices, and workplaces','Myrtle Beach is a travel market. Potential dates require independent review for distance, course duration, group size, instructor coverage, and any travel charge.')}
GTM="""<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f)})(window,document,'script','dataLayer','GTM-PQS8DCBH');</script>"""
RETAINED=('restaurants','churches','dental-offices','medical-offices','childcare','workplaces','aquatics')
DEPTH={
'restaurants':('Practice a guest choking response from recognition through handoff, a kitchen burn or cut, a fall in the dining room, and severe bleeding until EMS arrives.','AED placement should be visible to staff and reachable without crossing a locked office. Managers should know who calls 911, who meets responders, and who keeps the scene clear.','Short sessions before opening, between meal periods, or across two shift groups can protect service coverage. New-hire turnover makes a repeatable onboarding and renewal list especially useful.','Does a restaurant team need BLS?','Usually not. BLS is intended for healthcare and professional-rescuer roles unless an employer or contract specifically requires it.'),
'churches':('Practice a collapse during worship, a choking emergency at a meal, an injury during an event, and an infant or child emergency in the nursery.','AED access should account for locked buildings, multiple floors, large gatherings, and volunteers who may not know the property. Ushers and security teams can rehearse directing EMS.','Volunteer schedules, nursery coverage, weekend events, and mixed experience levels often favor staged groups with the same written response plan. Track new volunteers separately from expiring cardholders.','Who should be on a church response team?','A practical team may include ushers, security, clergy, ministry leaders, nursery volunteers, and staff who are commonly present during gatherings.'),
'dental-offices':('Practice syncope, cardiac or respiratory deterioration, team CPR around the dental chair, AED use, and a coordinated bag-mask response when the selected course and roles support it.','Review AED access, barrier devices, emergency oxygen or other practice equipment, exposure-control procedures, and who directs front-office staff during a clinical event.','Patient schedules make a whole-practice closure expensive. Clinical and front-office groups can be planned separately, while one coordinator tracks BLS, First Aid/CPR/AED, and Bloodborne Pathogens needs.','Does every dental employee need BLS?','No. Dentists, hygienists, assistants, and other clinical staff may need BLS; front-office roles may have a different requirement. Use the practice’s exact governing wording.'),
'medical-offices':('Practice the events the specialty can reasonably face, such as cardiac arrest, respiratory distress, severe allergic reaction, pediatric deterioration, bleeding, or a waiting-room emergency.','Confirm AED, bag-mask, emergency cart, medication, and room-access plans against the practice’s own scope and policies. Training should not imply ACLS or PALS is necessary for every clinic.','Separate clinical BLS, role-supported ACLS or PALS, and front-office First Aid/CPR/AED. Coordinate coverage around patient hours and keep one expiration view for new hires and renewals.','When are ACLS or PALS appropriate in an office?','Only when the specialty, employee role, employer, contract, or governing requirement supports that advanced course. They are not automatic additions to BLS.'),
'childcare':('Practice infant and child CPR, choking, severe allergic reaction, asthma, seizures, injuries, burns, and the handoff from classroom staff to the director and EMS.','Plan access to age-appropriate first-aid supplies and an AED when provided. Confirm how staff summon help while maintaining supervision and accounting for every child.','Ratios, nap schedules, pickup periods, licensing wording, and staff turnover shape delivery. Directors often need a plan for onboarding new staff between whole-team renewal cycles.','Which pediatric course should a childcare center choose?','Start with the exact licensing or employer wording. Pediatric First Aid/CPR/AED is a common fit, but the required certifying organization and delivery format must be confirmed.'),
'workplaces':('Practice sudden cardiac arrest, a fall, severe bleeding, burns or chemical exposure where relevant, and the exact internal alarm and EMS handoff process.','Designated responders should know AED and first-aid-kit locations, access restrictions, PPE, communication methods, and how site hazards affect scene safety.','Multiple shifts, production coverage, contractor rules, and site orientation can require staggered groups. Keep alternates trained and add new responders as staffing changes.','Is BLS the right workplace course?','Not for most general employee response teams. First Aid/CPR/AED is the usual starting point unless the employer or role specifically requires BLS.'),
'aquatics':('Practice drowning removal handoff, immediate ventilations and CPR, AED use in a wet environment, spinal or traumatic injury coordination, and pediatric response where patrons include children.','Review rescue equipment, bag-mask devices where appropriate, AED placement, communication across the pool deck, and a dry, controlled practice area.','Pool coverage cannot disappear during training. Lifeguard rotations, seasonal hiring, pre-opening sessions, and agency-specific credentials require early planning and frequent new-hire coordination.','Is ordinary CPR certification enough for lifeguards?','Often no. Lifeguards and professional rescuers may need BLS or an agency-specific credential. The employer or certifying agency’s exact requirement controls.')}
def page(slug,title,desc,h1,body,faq,kind,industry='',market='',related=''):
 url=f'{BASE}/group-training/{slug}/'; schema={'@context':'https://schema.org','@graph':[{'@type':'Organization','@id':f'{BASE}/#organization','name':'910CPR / Coastal CPR Training','url':BASE},{'@type':'Service','name':h1,'provider':{'@id':f'{BASE}/#organization'},'url':url,'areaServed':market or ['North Carolina','South Carolina']},{'@type':'BreadcrumbList','itemListElement':[{'@type':'ListItem','position':1,'name':'Home','item':BASE+'/'},{'@type':'ListItem','position':2,'name':'Group training','item':BASE+'/group-training.html'},{'@type':'ListItem','position':3,'name':h1,'item':url}]}]}
 recommended={'healthcare':'healthcare','childcare':'children','workplace':'workplace','community':'children','public_safety':'healthcare'}.get(industry,'complete')
 q=f'?industry={industry}&program={recommended}&market={escape(market)}&source_page_type={kind}'
 return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)} | 910CPR</title><meta name="description" content="{escape(desc)}"><meta name="robots" content="index,follow"><link rel="canonical" href="{url}"><link rel="stylesheet" href="/assets/group-training.css?v=20260906.2">{GTM}<script type="application/ld+json">{json.dumps(schema,separators=(',',':'))}</script></head><body><noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PQS8DCBH" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript><header class="top"><a class="brand" href="/index.html"><img src="/images/logo.png" alt=""><span>910CPR</span></a><a href="tel:+19103955193">910-395-5193</a></header><main><nav class="crumb" aria-label="Breadcrumb"><a href="/">Home</a> / <a href="/group-training.html">Group training</a> / {escape(h1)}</nav><article class="authority"><p class="kicker">{escape(kind.replace('_',' '))}</p><h1>{escape(h1)}</h1><p class="lede">{escape(desc)}</p>{body}<h2>What 910CPR needs to arrange training</h2><p>Share the complete training address, group size, employee roles, exact employer or licensing requirement, learning preference, workday constraints, and preferred dates. Choose a preferred time, and 910CPR will confirm travel, instructor availability, and final pricing before the class is scheduled.</p><h2>Certification and added practice</h2><p>A certification card applies only to its completed certification course and certifying organization. Bloodborne Pathogens, Bleeding Control, choking practice, and organization scenarios may be separate additions. American Heart Association, American Red Cross, and Health &amp; Safety Institute credentials are not interchangeable when a requirement names one.</p><h2>Common questions</h2>{faq}<p><a class="primary" href="/group-training.html{q}">Build a training plan for this team</a></p>{related}</article></main><script>window.dataLayer=window.dataLayer||[];window.dataLayer.push({{event:'group_training_view',industry:{json.dumps(industry or 'unknown')},market:{json.dumps(market or 'unknown')},recommended_program:'unknown',selected_program:'unknown',reservation_mode:'requires_confirmation',source_page_type:{json.dumps(kind)}}});</script></body></html>'''
def build():
 OUT.mkdir(parents=True,exist_ok=True)
 for slug in RETAINED:
  h1,audience,risks,roles,fit,industry,links=INDUSTRIES[slug];scenarios,equipment,operations,faq_q,faq_a=DEPTH[slug]
  body=f'<aside class="benefit-callout"><strong>Program summary</strong><span>{escape(fit)}</span></aside><section class="authority-section"><h2>Emergencies to prepare for</h2><p>{escape(risks)}</p></section><section class="authority-section"><h2>Who should be trained</h2><p>Consider {escape(roles)}. Match each person to the role and written requirement rather than placing everyone in one course.</p></section><section class="authority-section"><h2>Useful scenarios and supplemental practice</h2><p>{escape(scenarios)}</p></section><section class="authority-section"><h2>Equipment and response planning</h2><p>{escape(equipment)}</p></section><section class="authority-section"><h2>Scheduling, new hires, and renewals</h2><p>{escape(operations)}</p></section>'
  faq=f'<h3>{escape(faq_q)}</h3><p>{escape(faq_a)}</p><h3>Can training happen at our facility?</h3><p>Yes, when the address, room, group size, equipment plan, travel, and instructor schedule are confirmed.</p><h3>What does our coordinator need to provide?</h3><p>Employee roles, exact requirement wording, headcount, address, workday constraints, and preferred dates are enough to begin.</p>'
  rel='<h2>Related guidance</h2>'+''.join(f'<a href="/group-training/{x}/">{escape(INDUSTRIES[x][0])}</a><br>' for x in links if x in RETAINED)+'<p>Compare service planning for <a href="/group-training/wilmington-nc/">Wilmington</a>, <a href="/group-training/jacksonville-nc/">Jacksonville</a>, <a href="/group-training/lumberton-nc/">Lumberton</a>, <a href="/group-training/whiteville-nc/">Whiteville</a>, and <a href="/group-training/myrtle-beach-sc/">Myrtle Beach</a>.</p>'
  d=f'Role-based on-site CPR, AED, First Aid, and related training guidance for {audience}, with a simple path to request training.'
  dest=OUT/slug/'index.html';dest.parent.mkdir(parents=True,exist_ok=True);dest.write_text(page(slug,h1,d,h1,body,faq,'industry',industry,'',rel),encoding='utf-8')
 for slug,(market,county,nearby,orgs,truth) in LOCATIONS.items():
  h1=f'On-Site CPR Training in {market}';d=f'On-site CPR, First Aid, AED, BLS, and group-training guidance for organizations in {market} and reasonably served nearby communities.'
  body=f'<aside class="benefit-callout"><strong>Training at your location</strong><span>Choose a preferred time and we’ll confirm the instructor, travel, and final price with you.</span></aside><section class="authority-section"><h2>On-site service in {escape(market)}</h2><p>910CPR provides on-site training by confirmed request for {escape(orgs)}. {escape(truth)}</p></section><section class="authority-section"><h2>Nearby communities</h2><p>Requests may also be considered in {escape(nearby)}. Service is arranged for each organization after its address and training needs are reviewed.</p></section><section class="authority-section"><h2>Program summary</h2><ul class="program-summary"><li>BLS for healthcare and professional roles</li><li>First Aid, CPR, and AED for workplace teams</li><li>Pediatric training for childcare and youth programs</li><li>ACLS or PALS for supported clinical roles</li></ul><p>Bloodborne Pathogens, Bleeding Control, choking practice, and organization-specific scenarios may be added when appropriate.</p></section><section class="authority-section"><h2>Timing and pricing</h2><p>Group size, course length, instructor availability, equipment, the training address, and preferred dates can affect timing and price. Any time shown is a request until 910CPR confirms the details with you.</p></section>'
  faq=f'<h3>Can we use our own facility in {escape(market)}?</h3><p>Yes, after the address, room, furniture, accessibility, and practice space are reviewed.</p><h3>Are the same dates offered in every city?</h3><p>No. A potential time for {escape(market)} must pass its own travel and instructor review.</p><h3>What organizations commonly request training here?</h3><p>{escape(orgs.capitalize())} may request programs matched to their roles and written requirements.</p>'
  rel='<h2>Industry guidance</h2><p><a href="/group-training/dental-offices/">Dental offices</a>, <a href="/group-training/restaurants/">restaurants</a>, <a href="/group-training/churches/">churches</a>, <a href="/group-training/childcare/">childcare</a>, and <a href="/group-training/workplaces/">workplaces</a>.</p>'
  dest=OUT/slug/'index.html';dest.parent.mkdir(parents=True,exist_ok=True);dest.write_text(page(slug,h1,d,h1,body,faq,'location','',market,rel),encoding='utf-8')
if __name__=='__main__': build()
