-- P0: low-friction NHCSO email-code access.
-- No raw IP addresses are retained. Browser roles cannot read these authentication records.

create table if not exists public.nhcso_login_codes (
  id uuid primary key default gen_random_uuid(),
  email text not null,
  code_sha256 text not null,
  request_ip_sha256 text not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  attempt_count integer not null default 0 check (attempt_count between 0 and 5),
  consumed_at timestamptz,
  delivery_message_id text,
  delivery_error text
);

create index if not exists nhcso_login_codes_email_created_idx
  on public.nhcso_login_codes (email, created_at desc);
create index if not exists nhcso_login_codes_ip_created_idx
  on public.nhcso_login_codes (request_ip_sha256, created_at desc);

create table if not exists public.nhcso_login_attempts (
  id bigint generated by default as identity primary key,
  email_sha256 text not null,
  ip_sha256 text not null,
  succeeded boolean not null default false,
  attempted_at timestamptz not null default now()
);

create index if not exists nhcso_login_attempts_email_time_idx
  on public.nhcso_login_attempts (email_sha256, attempted_at desc);
create index if not exists nhcso_login_attempts_ip_time_idx
  on public.nhcso_login_attempts (ip_sha256, attempted_at desc);

create table if not exists public.nhcso_portal_sessions (
  id uuid primary key default gen_random_uuid(),
  token_sha256 text unique not null,
  email text not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  revoked_at timestamptz,
  created_ip_sha256 text not null,
  user_agent_sha256 text,
  last_seen_at timestamptz not null default now()
);

create index if not exists nhcso_portal_sessions_email_created_idx
  on public.nhcso_portal_sessions (email, created_at desc);
create index if not exists nhcso_portal_sessions_expires_idx
  on public.nhcso_portal_sessions (expires_at);

alter table public.nhcso_login_codes enable row level security;
alter table public.nhcso_login_attempts enable row level security;
alter table public.nhcso_portal_sessions enable row level security;

revoke all on table public.nhcso_login_codes from public, anon, authenticated;
revoke all on table public.nhcso_login_attempts from public, anon, authenticated;
revoke all on table public.nhcso_portal_sessions from public, anon, authenticated;

grant all on table public.nhcso_login_codes to service_role;
grant all on table public.nhcso_login_attempts to service_role;
grant all on table public.nhcso_portal_sessions to service_role;
grant usage, select on sequence public.nhcso_login_attempts_id_seq to service_role;
