begin;

create table public.landerware_courses(id text primary key,display_name text not null,provider text not null,delivery_mode text not null,public_slug text unique,listed boolean not null default false,enrollware_course_id text,active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.landerware_confirmation_templates(template_key text primary key,subject_template text not null,body_template text not null,delivery_provider text not null default 'gmail',active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.landerware_registration_profiles(
  profile_key text primary key,version integer not null default 1,course_id text not null,display_name text not null,
  listed boolean not null default false,registration_mode text not null,
  session_policy text not null check(session_policy in('required','optional','not_applicable')),
  allowed_entry_contexts text[] not null,required_fields jsonb not null default '[]',requirements jsonb not null default '[]',
  addons jsonb not null default '[]',payer_policy jsonb not null,pricing_behavior jsonb not null default '{}',
  corporate_context jsonb not null default '{}',confirmation_template_key text not null references public.landerware_confirmation_templates(template_key),
  completion_prerequisites jsonb not null default '[]',active boolean not null default true,
  created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.landerware_person_identities(identity_source text not null,identity_key text not null,person_id uuid not null references public.landerware_people(id),created_at timestamptz not null default now(),primary key(identity_source,identity_key));

alter table public.landerware_registrations alter column requirement_id drop not null,alter column session_id drop not null,alter column roster_id drop not null,
  add column idempotency_key text,add column course_id text,add column registration_profile_key text references public.landerware_registration_profiles(profile_key),
  add column registration_profile_snapshot jsonb not null default '{}',add column entry_context text,
  add column session_selection_status text not null default 'selected',add column selected_options jsonb not null default '{}',
  add column payer_mode text,add column pricing_state jsonb not null default '{}',add column payment_state text not null default 'not_required',
  add column billing_state text not null default 'not_required';
create unique index landerware_registration_idempotency on public.landerware_registrations(idempotency_key) where idempotency_key is not null;

create table public.landerware_registration_requirements(
  id uuid primary key default gen_random_uuid(),registration_id uuid not null references public.landerware_registrations(id),person_id uuid not null references public.landerware_people(id),
  requirement_key text not null,requirement_type text not null,display_name text not null,
  required_before_registration boolean not null default false,required_before_attendance boolean not null default false,required_before_completion boolean not null default false,
  upload_now boolean not null default false,submit_later boolean not null default false,staff_may_satisfy boolean not null default false,
  upload_config jsonb not null default '{}',status text not null default 'pending',satisfied_at timestamptz,satisfied_by text,
  document_ids jsonb not null default '[]',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(registration_id,requirement_key));
create table public.landerware_document_submission_tokens(id uuid primary key default gen_random_uuid(),token_sha256 text not null unique,person_id uuid not null references public.landerware_people(id),registration_id uuid not null references public.landerware_registrations(id),registration_requirement_id uuid not null references public.landerware_registration_requirements(id),expires_at timestamptz not null,revoked_at timestamptz,last_opened_at timestamptz,submission_count integer not null default 0,created_at timestamptz not null default now());

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('landerware-requirement-documents','landerware-requirement-documents',false,10485760,array['application/pdf','image/jpeg','image/png','image/webp']) on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
insert into public.landerware_courses values('aha-heartsaver-skills-session','AHA Heartsaver Skills Session','American Heart Association','skills_session','heartsaver-skills',false,null,true,now(),now());
insert into public.landerware_confirmation_templates(template_key,subject_template,body_template) values
('heartsaver-skills-confirmation-v1','{{display_name}} registration confirmed','Hi {{first_name}},\n\nYour {{display_name}} registration is confirmed.\n\n{{requirement_message}}\n\n910CPR\n910-395-5193'),
('standard-registration-confirmation-v1','You’re registered — {{display_name}}','Hi {{first_name}},\n\nYou’re registered for {{display_name}}.\n\n{{session_message}}\n{{payer_message}}\n\n910CPR\n910-395-5193');
insert into public.landerware_registration_profiles(profile_key,course_id,display_name,listed,registration_mode,session_policy,allowed_entry_contexts,required_fields,requirements,addons,payer_policy,pricing_behavior,corporate_context,confirmation_template_key,completion_prerequisites) values
('aha-heartsaver-skills-public','aha-heartsaver-skills-session','AHA Heartsaver Skills Session',false,'public_direct','optional',array['public_anonymous','secure_known_person','staff_admin'],
 '["first_name","last_name","email","online_completed_acknowledgement"]',
 '[{"key":"aha_online_completion","type":"AHA_ONLINE_COMPLETION_CERTIFICATE","display_name":"AHA online-course completion certificate","required_before_registration":false,"required_before_attendance":true,"required_before_completion":true,"upload_now":true,"submit_later":true,"staff_may_satisfy":true,"upload":{"field":"certificate","max_bytes":10485760,"mime_types":["application/pdf","image/jpeg","image/png","image/webp"],"token_days":180}}]',
 '[]','{"mode":"customer_pays"}','{"mode":"profile_price","amount_cents":0}','{}','heartsaver-skills-confirmation-v1','["aha_online_completion"]');
insert into public.landerware_registration_profiles(profile_key,course_id,display_name,listed,registration_mode,session_policy,allowed_entry_contexts,required_fields,requirements,addons,payer_policy,pricing_behavior,corporate_context,confirmation_template_key,completion_prerequisites)
select 'maxim-course-'||course_id,course_id,display_name,false,'corporate_scheduling','required',array['maxim_staff','employee_self_service'],
  '["first_name","last_name"]'::jsonb,'[]'::jsonb,'[]'::jsonb,'{"mode":"corporate_client_pays"}'::jsonb,
  '{"mode":"corporate_contract"}'::jsonb,'{"organization":"MAXIM","billing_account_required":true}'::jsonb,
  'standard-registration-confirmation-v1','[]'::jsonb
from(values('209806','AHA BLS Provider'),('359474','AHA BLS Renewal'),('210549','AHA HeartCode BLS Skills'),
  ('209809','AHA Heartsaver First Aid CPR AED'),('329495','AHA Heartsaver Online + Skills')) as courses(course_id,display_name);

insert into public.landerware_courses values('landerware-foundations','Foundations Instructor-Led Group Course','910CPR','instructor_led_group','foundations',false,null,true,now(),now());
insert into public.landerware_confirmation_templates(template_key,subject_template,body_template) values
('group-course-confirmation-v1','You’re registered — {{display_name}}','Hi {{first_name}},\n\nYou’re registered for {{display_name}}.\n\n{{session_message}}\n{{requirement_message}}\n{{payer_message}}\n\n910CPR\n910-395-5193');
insert into public.landerware_registration_profiles(profile_key,course_id,display_name,listed,registration_mode,session_policy,allowed_entry_contexts,required_fields,requirements,addons,payer_policy,pricing_behavior,corporate_context,confirmation_template_key,completion_prerequisites) values
('nhcso-foundations-instructor-led-v1','landerware-foundations','Foundations Instructor-Led Group Course',false,'instructor_led_group','required',array['corporate_employee','staff_admin','roster_import'],
 '["first_name","last_name","email"]',
 '[{"key":"signed_form","type":"SIGNED_FORM","display_name":"Signed course form","required_before_registration":true,"required_before_attendance":true,"required_before_completion":true,"upload_now":true,"submit_later":false,"staff_may_satisfy":false,"upload":{"field":"signedForm","max_bytes":10485760,"mime_types":["application/pdf","image/jpeg","image/png"],"token_days":30}},{"key":"employer_document","type":"EMPLOYER_DOCUMENT","display_name":"Employer document","required_before_registration":false,"required_before_attendance":true,"required_before_completion":true,"upload_now":false,"submit_later":true,"staff_may_satisfy":true,"upload":{"field":"employerDocument","max_bytes":10485760,"mime_types":["application/pdf","image/jpeg","image/png"],"token_days":45}}]',
 '[]','{"mode":"invoice_later"}','{"mode":"contract_rate","currency":"USD"}','{"organization":"NHCSO","billing_account":"NHCSO-TRAINING"}','group-course-confirmation-v1','["signed_form","employer_document"]');

create or replace function public.landerware_create_or_find_person(p_first_name text,p_last_name text,p_email text default null,p_phone text default null,p_existing_person_id uuid default null,p_identity_source text default null,p_identity_key text default null)
returns jsonb language plpgsql security definer set search_path='' as $$
declare v_person public.landerware_people;v_email text:=lower(trim(coalesce(p_email,'')));v_phone text:=regexp_replace(coalesce(p_phone,''),'[^0-9]','','g');v_created boolean:=false;
begin
 if p_existing_person_id is not null then select * into v_person from public.landerware_people where id=p_existing_person_id for update;
 elsif p_identity_source is not null and p_identity_key is not null then perform pg_advisory_xact_lock(hashtextextended('identity|'||p_identity_source||'|'||p_identity_key,0));select p.* into v_person from public.landerware_person_identities i join public.landerware_people p on p.id=i.person_id where i.identity_source=p_identity_source and i.identity_key=p_identity_key for update of p;
 elsif v_email<>'' then perform pg_advisory_xact_lock(hashtextextended('email|'||v_email,0));select * into v_person from public.landerware_people where archived_at is null and lower(trim(coalesce(current_email,'')))=v_email order by created_at limit 1 for update;
 elsif v_phone<>'' then perform pg_advisory_xact_lock(hashtextextended('phone|'||v_phone||lower(trim(p_first_name))||lower(trim(p_last_name)),0));select * into v_person from public.landerware_people where archived_at is null and regexp_replace(coalesce(current_phone,''),'[^0-9]','','g')=v_phone and lower(trim(current_first_name))=lower(trim(p_first_name)) and lower(trim(current_last_name))=lower(trim(p_last_name)) order by created_at limit 1 for update;end if;
 if v_person.id is null then if trim(coalesce(p_first_name,''))='' or trim(coalesce(p_last_name,''))='' then raise exception 'first_and_last_name_required';end if;insert into public.landerware_people(current_first_name,current_last_name,current_email,current_phone,searchable_text) values(trim(p_first_name),trim(p_last_name),nullif(v_email,''),nullif(trim(coalesce(p_phone,'')),''),lower(trim(p_first_name)||' '||trim(p_last_name)||' '||v_email||' '||coalesce(p_phone,''))) returning * into v_person;v_created:=true;
 else update public.landerware_people set current_first_name=coalesce(nullif(trim(p_first_name),''),current_first_name),current_last_name=coalesce(nullif(trim(p_last_name),''),current_last_name),current_email=coalesce(nullif(v_email,''),current_email),current_phone=coalesce(nullif(trim(coalesce(p_phone,'')),''),current_phone),updated_at=now() where id=v_person.id returning * into v_person;end if;
 if p_identity_source is not null and p_identity_key is not null then insert into public.landerware_person_identities values(p_identity_source,p_identity_key,v_person.id,now()) on conflict(identity_source,identity_key) do nothing;end if;
 return jsonb_build_object('personId',v_person.id,'created',v_created);end $$;

create or replace function public.landerware_register(p_profile_key text,p_entry_context text,p_fields jsonb,p_idempotency_key text,p_selected_options jsonb default '{}',p_organization_id uuid default null,p_existing_person_id uuid default null,p_identity_source text default null,p_identity_key text default null,p_external_session_id text default null,p_starts_at timestamptz default null,p_location_name text default null,p_provenance text default null,p_requirements_manifest jsonb default '{}')
returns jsonb language plpgsql security definer set search_path='' as $$
declare v_profile public.landerware_registration_profiles;v_person jsonb;v_person_id uuid;v_session public.landerware_sessions;v_roster public.landerware_rosters;v_reg public.landerware_registrations;v_req jsonb;v_required text;v_req_ids jsonb:='[]';v_req_id uuid;v_payer text;
begin
 select * into v_profile from public.landerware_registration_profiles where profile_key=p_profile_key and active=true;if v_profile.profile_key is null then raise exception 'registration_profile_not_found';end if;
 if not(p_entry_context=any(v_profile.allowed_entry_contexts)) then raise exception 'entry_context_not_allowed';end if;if v_profile.session_policy='required' and(p_external_session_id is null or p_starts_at is null) then raise exception 'session_required';end if;
 for v_required in select jsonb_array_elements_text(v_profile.required_fields) loop if nullif(trim(coalesce(p_fields->>v_required,'')),'') is null then raise exception 'required_field_missing:%',v_required;end if;end loop;
 select * into v_reg from public.landerware_registrations where idempotency_key=p_idempotency_key limit 1;if v_reg.id is not null then select coalesce(jsonb_agg(id),'[]') into v_req_ids from public.landerware_registration_requirements where registration_id=v_reg.id;return jsonb_build_object('personId',v_reg.person_id,'registrationId',v_reg.id,'sessionId',v_reg.session_id,'requirementIds',v_req_ids,'idempotentReplay',true);end if;
 v_person:=public.landerware_create_or_find_person(p_fields->>'first_name',p_fields->>'last_name',p_fields->>'email',p_fields->>'phone',p_existing_person_id,p_identity_source,p_identity_key);v_person_id:=(v_person->>'personId')::uuid;
 if p_external_session_id is not null and p_starts_at is not null then insert into public.landerware_sessions(external_session_id,course_id,course_name,starts_at,location_name,organization_id,provenance,requirements_manifest) values(p_external_session_id,v_profile.course_id,v_profile.display_name,p_starts_at,p_location_name,p_organization_id,coalesce(p_provenance,p_entry_context),p_requirements_manifest) on conflict(external_session_id,course_id,starts_at) do update set updated_at=now() returning * into v_session;insert into public.landerware_rosters(session_id) values(v_session.id) on conflict(session_id) do update set updated_at=now() returning * into v_roster;end if;
 v_payer:=v_profile.payer_policy->>'mode';if v_payer not in('customer_pays','corporate_client_pays','invoice_later','prepaid','free','special_price') then raise exception 'unsupported_payer_mode';end if;insert into public.landerware_registrations(person_id,session_id,roster_id,organization_id,status,source,idempotency_key,course_id,registration_profile_key,registration_profile_snapshot,entry_context,session_selection_status,selected_options,payer_mode,pricing_state,payment_state,billing_state) values(v_person_id,v_session.id,v_roster.id,p_organization_id,'active',p_entry_context,p_idempotency_key,v_profile.course_id,v_profile.profile_key,to_jsonb(v_profile),p_entry_context,case when v_session.id is null then 'pending' else 'selected' end,p_selected_options,v_payer,v_profile.pricing_behavior,case when v_payer in('customer_pays','special_price') then 'pending' else 'not_required' end,case when v_payer in('corporate_client_pays','invoice_later') then 'pending' else 'not_required' end) returning * into v_reg;
 for v_req in select * from jsonb_array_elements(v_profile.requirements) loop insert into public.landerware_registration_requirements(registration_id,person_id,requirement_key,requirement_type,display_name,required_before_registration,required_before_attendance,required_before_completion,upload_now,submit_later,staff_may_satisfy,upload_config,status) values(v_reg.id,v_person_id,v_req->>'key',v_req->>'type',v_req->>'display_name',coalesce((v_req->>'required_before_registration')::boolean,false),coalesce((v_req->>'required_before_attendance')::boolean,false),coalesce((v_req->>'required_before_completion')::boolean,false),coalesce((v_req->>'upload_now')::boolean,false),coalesce((v_req->>'submit_later')::boolean,false),coalesce((v_req->>'staff_may_satisfy')::boolean,false),coalesce(v_req->'upload','{}'),case when coalesce((v_req->>'required_before_registration')::boolean,false) then 'required_now' else 'pending' end) returning id into v_req_id;v_req_ids:=v_req_ids||to_jsonb(v_req_id);end loop;
 if v_roster.id is not null then insert into public.landerware_roster_memberships(roster_id,session_id,person_id,registration_id,display_name,email,source) values(v_roster.id,v_session.id,v_person_id,v_reg.id,trim(coalesce(p_fields->>'first_name',''))||' '||trim(coalesce(p_fields->>'last_name','')),p_fields->>'email',p_entry_context);end if;
 insert into public.landerware_activity_events(event_type,actor_source,person_id,organization_id,registration_id,session_id,details) values('registration_created',case when p_entry_context in('maxim_staff','employee_self_service','brian_admin','instructor','system','enrollware_import') then p_entry_context else 'system' end,v_person_id,p_organization_id,v_reg.id,v_session.id,jsonb_build_object('profileKey',p_profile_key,'entryContext',p_entry_context));
 return jsonb_build_object('personId',v_person_id,'registrationId',v_reg.id,'sessionId',v_session.id,'requirementIds',v_req_ids,'idempotentReplay',false,'profileKey',v_profile.profile_key);end $$;

create table public.landerware_completions(id uuid primary key default gen_random_uuid(),registration_id uuid not null unique references public.landerware_registrations(id),person_id uuid not null references public.landerware_people(id),course_id text not null,session_id uuid references public.landerware_sessions(id),completed_at timestamptz not null,completion_status text not null,recorded_by text not null,details jsonb not null default '{}',created_at timestamptz not null default now());
alter table public.landerware_credentials add column session_id uuid references public.landerware_sessions(id),add column credential_type text,add column credential_status text not null default 'issued';

create or replace function public.landerware_satisfy_registration_requirement(p_requirement_id uuid,p_actor text,p_details jsonb default '{}') returns jsonb language plpgsql security definer set search_path='' as $$
declare v_req public.landerware_registration_requirements;
begin select * into v_req from public.landerware_registration_requirements where id=p_requirement_id for update;if v_req.id is null then raise exception 'requirement_not_found';end if;if not v_req.staff_may_satisfy and p_actor like 'staff:%' then raise exception 'staff_satisfaction_not_allowed';end if;update public.landerware_registration_requirements set status='satisfied',satisfied_at=now(),satisfied_by=p_actor,updated_at=now() where id=v_req.id;insert into public.landerware_activity_events(event_type,actor_source,person_id,registration_id,details) values('requirement_satisfied','system',v_req.person_id,v_req.registration_id,jsonb_build_object('requirementId',v_req.id,'actor',p_actor,'details',p_details));return jsonb_build_object('requirementId',v_req.id,'status','satisfied');end $$;

create or replace function public.landerware_record_completion(p_registration_id uuid,p_completed_at timestamptz,p_recorded_by text,p_details jsonb default '{}') returns jsonb language plpgsql security definer set search_path='' as $$
declare v_reg public.landerware_registrations;v_blockers integer;v_completion public.landerware_completions;
begin select * into v_reg from public.landerware_registrations where id=p_registration_id for update;if v_reg.id is null then raise exception 'registration_not_found';end if;select count(*) into v_blockers from public.landerware_registration_requirements where registration_id=v_reg.id and required_before_completion=true and status<>'satisfied';if v_blockers>0 then raise exception 'completion_prerequisites_unsatisfied';end if;insert into public.landerware_completions(registration_id,person_id,course_id,session_id,completed_at,completion_status,recorded_by,details) values(v_reg.id,v_reg.person_id,v_reg.course_id,v_reg.session_id,p_completed_at,'completed',p_recorded_by,p_details) on conflict(registration_id) do update set completed_at=excluded.completed_at,recorded_by=excluded.recorded_by,details=excluded.details returning * into v_completion;update public.landerware_registrations set status='completed',updated_at=now() where id=v_reg.id;insert into public.landerware_activity_events(event_type,actor_source,person_id,registration_id,session_id,details) values('registration_completed','system',v_reg.person_id,v_reg.id,v_reg.session_id,jsonb_build_object('completionId',v_completion.id,'recordedBy',p_recorded_by));return jsonb_build_object('completionId',v_completion.id,'registrationId',v_reg.id,'personId',v_reg.person_id,'courseId',v_reg.course_id,'sessionId',v_reg.session_id);end $$;

create or replace function public.landerware_issue_credential(p_registration_id uuid,p_credential_type text,p_ecard_code text,p_ecard_url text,p_issued_at timestamptz,p_expires_on date,p_actor text) returns jsonb language plpgsql security definer set search_path='' as $$
declare v_reg public.landerware_registrations;v_completion public.landerware_completions;v_credential public.landerware_credentials;
begin select * into v_reg from public.landerware_registrations where id=p_registration_id;select * into v_completion from public.landerware_completions where registration_id=p_registration_id;if v_reg.id is null then raise exception 'registration_not_found';end if;if v_completion.id is null then raise exception 'completion_required_before_credential';end if;insert into public.landerware_credentials(person_id,registration_id,course_id,session_id,credential_type,ecard_code,ecard_url,issued_at,expires_on) values(v_reg.person_id,v_reg.id,v_reg.course_id,v_reg.session_id,p_credential_type,p_ecard_code,p_ecard_url,p_issued_at,p_expires_on) returning * into v_credential;insert into public.landerware_activity_events(event_type,actor_source,person_id,registration_id,session_id,details) values('credential_issued','system',v_reg.person_id,v_reg.id,v_reg.session_id,jsonb_build_object('credentialId',v_credential.id,'credentialType',p_credential_type,'ecardCode',p_ecard_code,'actor',p_actor,'ecardUrl',p_ecard_url));return jsonb_build_object('credentialId',v_credential.id,'personId',v_reg.person_id,'registrationId',v_reg.id,'courseId',v_reg.course_id,'sessionId',v_reg.session_id);end $$;

revoke execute on function public.landerware_create_or_find_person(text,text,text,text,uuid,text,text) from public,anon,authenticated;revoke execute on function public.landerware_register(text,text,jsonb,text,jsonb,uuid,uuid,text,text,text,timestamptz,text,text,jsonb) from public,anon,authenticated;
grant execute on function public.landerware_create_or_find_person(text,text,text,text,uuid,text,text) to service_role;grant execute on function public.landerware_register(text,text,jsonb,text,jsonb,uuid,uuid,text,text,text,timestamptz,text,text,jsonb) to service_role;
revoke execute on function public.landerware_satisfy_registration_requirement(uuid,text,jsonb),public.landerware_record_completion(uuid,timestamptz,text,jsonb),public.landerware_issue_credential(uuid,text,text,text,timestamptz,date,text) from public,anon,authenticated;
grant execute on function public.landerware_satisfy_registration_requirement(uuid,text,jsonb),public.landerware_record_completion(uuid,timestamptz,text,jsonb),public.landerware_issue_credential(uuid,text,text,text,timestamptz,date,text) to service_role;
alter table public.landerware_courses enable row level security;alter table public.landerware_confirmation_templates enable row level security;alter table public.landerware_registration_profiles enable row level security;alter table public.landerware_person_identities enable row level security;alter table public.landerware_registration_requirements enable row level security;alter table public.landerware_document_submission_tokens enable row level security;
alter table public.landerware_completions enable row level security;
revoke all on public.landerware_courses,public.landerware_confirmation_templates,public.landerware_registration_profiles,public.landerware_person_identities,public.landerware_registration_requirements,public.landerware_document_submission_tokens from anon,authenticated;
revoke all on public.landerware_completions from anon,authenticated;
commit;
