# From your repo root
Set-Location "D:\Users\ten77\Documents\GitHub\910cpr-class-landers"

# Make the Actions folder
New-Item -ItemType Directory -Force ".github\workflows" | Out-Null

# Create the workflow file
@'
name: Deploy Pages
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build site from latest CSV in data
        run: |
          python scripts/build_from_hovn.py
          python scripts/make_sessions_sitemap.py
          python scripts/make_course_hubs.py

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4
'@ | Set-Content ".github\workflows\pages.yml" -Encoding UTF8

# Quick verify
cmd /c "tree /F /A .github"
type ".github\workflows\pages.yml"
