name: Update sitemap automatically
on:
  push:
    branches: [ main ]
    paths:
      - "courses/**"
      - "index.html"
      - ".github/workflows/sitemap_update.yml"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate sitemap.xml
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml
          echo "  <url><loc>https://910cpr.com/</loc></url>" >> sitemap.xml
          echo "  <url><loc>https://910cpr.com/courses/</loc></url>" >> sitemap.xml
          for f in $(find courses -name '*.html' | sort); do
            echo "  <url><loc>https://910cpr.com/${f}</loc></url>" >> sitemap.xml
          done
          echo '</urlset>' >> sitemap.xml
      - name: Commit sitemap if changed
        run: |
          if git diff --quiet -- sitemap.xml; then
            echo "No sitemap changes"; exit 0; fi
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add sitemap.xml
          git commit -m "chore: auto-update sitemap [skip ci]"
          git push
