name: Update Enrollware Schedule
on:
  schedule:
    - cron: "0 * * * *"   # hourly; adjust as needed
  workflow_dispatch: {}    # allow manual runs

jobs:
  refresh:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch Enrollware schedule HTML
        run: |
          mkdir -p shared
          curl -sSL -A "Mozilla/5.0 (compatible; 910CPR-ScheduleBot/1.0)" \
            "https://coastalcprtraining.enrollware.com/schedule" \
            -o shared/schedule.html

      - name: Commit if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: shared/schedule.html
          commit_message: "Auto-update: Enrollware schedule snapshot"
